### ISSUE TITLE
Design considerations

### ISSUE THREAD

**Issue by rtrauntvein** [cachethq/Docker#1]
As this gets split out from Cachet core, we have an opportunity to get our design in order.  This issue is to open the discussion to the rest of the contributors. 

A few of the objectives to think about:

- [x] Pull Cachet release tag from Git corresponding to image:version
- [x] Use of a base image to speed up builds

**Comment by wfjsw** [comment]
Merging file directly or set a `git clone` on Dockerfile?

**Comment by jbrooksuk** [comment]
Yeah, `git clone` the `CachetHQ/Cachet` code is ideal since we do not want the core Cachet code within the repo.

**Comment by GrahamCampbell** [comment]
It would be better to download archives from githyb rather than using git.

**Comment by jbrooksuk** [comment]
Archives :+1:

**Comment by rtrauntvein** [comment]
Need to setup the hub builds still, and the rest of the releases.

**Comment by GrahamCampbell** [comment]
Also, is there any chance we can use postgres rather than mysql?

**Comment by rtrauntvein** [comment]
Sure, should be fine.
