### ISSUE TITLE
Base image layer optimization

### ISSUE THREAD

**Issue by rtrauntvein** [cachethq/Docker#10]
I think we can put more of the layers into the `:base` image - Namely I am thinking that the `entrypoint.sh` and `.env.docker` could just be in the base image also

**Comment by wfjsw** [comment]
entrypoint.sh may change in future if env-config is changed. Don't want to rely on base too much :smile:

**Comment by rtrauntvein** [comment]
We could just tag base also - Have seen projects do something like `namespace:base-20150817` that way we can have `:base` releases also.

Currently it is `:base-hash` which is essentially the same.
