### ISSUE TITLE
I get an error with docker-compose --verbose up 

### ISSUE THREAD

**Issue by posix4e** [CachetHQ/Docker#108]
posi@docker:~/Desktop/Docker$ docker-compose --version
docker-compose version 1.7.1, build 6c29830
posi@docker:~/Desktop/Docker$ docker --version
Docker version 1.10.3, build 20f81dd
posi@docker:~/Desktop/Docker$ uname -a
Linux docker 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
posi@docker:~/Desktop/Docker$ 

[foo.txt](https://github.com/CachetHQ/Docker/files/370441/foo.txt) <- logfile

**Comment by posix4e** [comment]
git hash 091984f941e568b88b2519270f1dfb204abf8716

**Comment by djdefi** [comment]
2.3.0-RC6 is not stable, does this issue occur using the v2.2.4 release / tag?

The error in your log seems to be related to docker-compose itself:

```
ERROR: for nginx  Cannot start container 3cfed33ac8994a5adea9e36e1d23d832ba89fd89de0aee40ceb9e45aaf26e64f: [10] System error: could not synchronise with container process
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 63, in main
    log.error(e.msg)
AttributeError: 'ProjectError' object has no attribute 'msg'
```

**Comment by djdefi** [comment]
Please re-open if still having this issue with 2.3.7 release.
