### ISSUE TITLE
Outdated documentation regarding key generation and app initialization ?

### ISSUE THREAD

**Issue by dmsimard** [CachetHQ/Docker#110]
I'm testing a fresh checkout of the latest tag at time of writing ( v2.3.0-RC6 ).

The [documentation](https://docs.cachethq.io/docs/get-started-with-docker) mentions needing to run:

    $ docker exec -i docker_cachet_1  php artisan key:generate
    $ docker exec -i docker_cachet_1  php artisan app:install

However, it looks like a unique key (confirmed by running more than once) is generated every time and the application is already installed (through entrypoint script).

**Comment by djdefi** [comment]
v2.3.0-RC6 is not quite stable yet, so it may need some changes before 2.3.0 is released fully. I haven't done a lot of testing on 2.3 yet.

cc: @jbrooksuk @GrahamCampbell

**Comment by djdefi** [comment]
I didn't realize 2.3.x was released upstream, will try to get those updated this week here. Sorry for the delay!

**Comment by dmsimard** [comment]
Ping :)

Would also love an update of the image on https://hub.docker.com/r/cachethq/docker/

**Comment by djdefi** [comment]
Build are in progress on Docker hub. `php artisan key:generate` is not part of the entrypoint in 2.3.x

Please re-open if you have any further issues.
