### ISSUE TITLE
Pinned package are not present anymore in debain repo

### ISSUE THREAD

**Issue by sapk** [CachetHQ/Docker#112]
The version 5.6.22+dfsg-0+deb8u1 (the one used in master branch) is not present anymore.
Repo : http://security.debian.org/debian-security/pool/updates/main/p/php5/

The pinning was made here : https://github.com/CachetHQ/Docker/pull/98

This is blocking for the building of the image.

**Comment by djdefi** [comment]
Thanks for the report. I am thinking that we should just drop the package pinning at this point.
