### ISSUE TITLE
Ngnix will not start with docker-compose

### ISSUE THREAD

**Issue by gamkiller77** [CachetHQ/Docker#120]
I followed the doc on how to deploy using docker-compose but ever time I do a docker-compose up everything start find but the ngnix server.  Here is the error code i am getting.

nginx_1     | 2016/08/19 19:07:12 [emerg] 1#1: open() "/etc/nginx/conf.d/default.conf" failed (13: Permission denied) in /etc/nginx/nginx.conf:31
nginx_1     | nginx: [emerg] open() "/etc/nginx/conf.d/default.conf" failed (13: Permission denied) in /etc/nginx/nginx.conf:31
cachetdocker_nginx_1 exited with code 1

**Comment by djdefi** [comment]
Hi @gamkiller77, sorry to hear about the trouble.

Can you give me a few pieces of info related to you setup:

* Docker Host OS / Platform
* Docker Version
* Docker Compose version
* Cachet release

This seems like it could be a host filesystem permissions issue, as that config file is mounted in via a volume by compose. Can you please also run `ls -la` inside of your clone of this repo?

**Comment by gamkiller77** [comment]
Red Hat Enterprise Linux Server release 7.2 (Maipo)

Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-46.el7.10.x86_64
 Go version:      go1.6.2
 Git commit:      2a93377-unsupported
 Built:           Fri Jul 29 13:45:25 2016
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-46.el7.10.x86_64
 Go version:      go1.6.2
 Git commit:      2a93377-unsupported
 Built:           Fri Jul 29 13:45:25 2016
 OS/Arch:         linux/amd64


docker-compose version 1.8.0, build 94f7016
docker-py version: 1.9.0
CPython version: 2.7.5
OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013


2.3

**Comment by gamkiller77** [comment]
total 68
drwxr-xr-x.  5 root root 4096 Aug 18 17:33 .
dr-xr-x---. 12 root root 4096 Aug 19 19:27 ..
-rw-r--r--.  1 root root  853 Aug 16 19:21 cachet-deployment.yaml
drwxr-xr-x.  2 root root 4096 Aug 16 19:18 conf
-rw-r--r--.  1 root root 1216 Aug 16 19:18 CONTRIBUTING.md
-rw-r--r--.  1 root root  720 Aug 16 19:18 docker-compose.yml
-rw-r--r--.  1 root root 2320 Aug 18 17:33 Dockerfile
-rw-r--r--.  1 root root  125 Aug 16 19:18 .dockerignore
-rwxr-xr-x.  1 root root 3890 Aug 16 19:18 entrypoint.sh
drwxr-xr-x.  8 root root 4096 Aug 18 17:33 .git
-rw-r--r--.  1 root root 1503 Aug 16 19:18 LICENSE
-rw-r--r--.  1 root root  270 Aug 16 19:18 Makefile
-rw-r--r--.  1 root root  734 Aug 16 19:21 nginx-deployment.yaml
-rw-r--r--.  1 root root  246 Aug 16 19:21 nginx-svc.yaml
-rw-r--r--.  1 root root  762 Aug 16 19:21 postgres-deployment.yaml
-rw-r--r--.  1 root root 1736 Aug 16 19:18 README.md
drwxr-xr-x.  3 root root   87 Aug 16 19:18 test
-rw-r--r--.  1 root root  985 Aug 16 19:19 .travis.yml

**Comment by gamkiller77** [comment]
I did send a message to Cachet support and i got this.


James replied
Aug 22, 13:36
Hi Andy,

Ryan has said:

Sounds like messed up permissions in their clone I believe. The `default.conf` is bind mounted into the nginx container with compose

**Comment by gamkiller77** [comment]
got this to work in openshift.

**Comment by MarcusMann** [comment]
In your terminal run the command:

    sudo setenfonce 0

Now, re-run the docker command.
