### ISSUE TITLE
Permission denied on start cachet

### ISSUE THREAD

**Issue by sebglon** [CachetHQ/Docker#124]
afert fresh checkout on git repo master

I run docker-compose buid and docker-compose up.

container cachet exit with non 0.
on log i see: 
```"/sbin/entrypoint.sh": permission denied```

If i edit Dockerfile and add 
```RUN chmod 0777 /sbin/entrypoint.sh```

or move  
```COPY entrypoint.sh /sbin/entrypoint.sh```
after ```USER www-data```

all is OK

**Comment by sebglon** [comment]
this is cause by my FS that is Windows share on my linux

**Comment by sebglon** [comment]
this bug is due to COPY comamnd.
/sbin/entrypoint.sh and /var/www/html/.env has owner root.

If i add ```USER root``` before ENTRYPOINT line, All is OK but Cachet is run on root user.

If we want to run php and cron on user www-data, you can add user param on supervisor.conf
example:
```
[program:php-fpm]
command=/usr/sbin/php5-fpm -c /etc/php5/fpm
user=www-data
```

**Comment by djdefi** [comment]
May be a local permissions issue, possibly do a `chmod a+x entrypoint.sh` within your working directory.

Travis CI builds are not failing, which I would expect if this was a more widespread issue.

**Comment by sebglon** [comment]
A have tested chmod a+x and it not solve this

**Comment by djdefi** [comment]
Our Travis tests build and run the container as well.

Anyway, I have created #134 which chmod / chown's the `entrypoint.sh` to `www-data` during build.
