### ISSUE TITLE
Email Not Sending Out, Subscribe Button Missing

### ISSUE THREAD

**Issue by apssupport** [CachetHQ/Docker#125]
Hello,

Just installed and ran the latest docker image of cachet, installation went smoothly, but Cachet is not sending out emails and the subscribe button is not on the footer (even though it is checked off in settings).

**Comment by apssupport** [comment]
After reinstalling, the button is there, but I am getting a 500 error code all the time when an email should be sent out. When trying to subscribe from the front page or the back, or invite team member.

**Comment by djdefi** [comment]
This may be addressed by https://github.com/CachetHQ/Cachet/pull/2295

**Comment by gamkiller77** [comment]
So I have Cachet up and running perfectly in OpenShift 3.3 / kubernetes 1.3.  I have passed all the ENV needed to setup email and checked the allow users to subscribe but the link is not visible on the site at all.

I did not want to dup the topic issue but this is a problem.

Running code 2.3.10

I am hoping 2.4 will fix this.

**Comment by djdefi** [comment]
There have been lots of updates since this was opened, and we haven't heard back from you. Please try the latest master or tagged release, and open a new issue if you are still having issues.
