### ISSUE TITLE
Container command '/sbin/entrypoint.sh' not found or does not exist.

### ISSUE THREAD

**Issue by NioTeX** [CachetHQ/Docker#136]
```
ERROR: for cachet  Cannot start service cachet: Container command '/sbin/entrypoint.sh' not found or does not exist.
```

I get this error when running `docker-compose up`

Really strange since I inspected the `Dockerfile` and saw that it had `COPY entrypoint.sh /sbin/entrypoint.sh` in it

Any ideas? I am using `v2.3.9` of the repository

**Comment by djdefi** [comment]
Could be permissions I suppose. In #134 we added a [`chmod` / `chown` of that file](https://github.com/CachetHQ/Docker/commit/0d65dd1c2c665c4828d89ce891c12479207684b6)

**Comment by djdefi** [comment]
I have not been able to reproduce this, feel free to reopen with any additional details if still relevant.
