### ISSUE TITLE
Out of the box, hitting the main endpoint with https:// redirects to http:// endpoints 

### ISSUE THREAD

**Issue by ryanwalls** [CachetHQ/Docker#14]
I've configured a separate load balancer to handle https://.  But when trying to login and clicking any links in the UI, the app is specifying http:// endpoints.  Since I've blocked port 80 access on my 3rd party load balancer, the app doesn't work other than the main page.  

Is there a way to make the redirects/links relative so they don't specify http?

**Comment by djdefi** [comment]
May need to add some sort of rewrite to force https://

My Cachet page seems to be behaving the same way, however my domain is HSTS preloaded so it forces https at the browser level.

What type of load balancer are you utilizing? Haproxy or something?

**Comment by ryanwalls** [comment]
@djdefi I'm using an amazon ELB.  So unfortunately, not much rewrite-ability.

**Comment by djdefi** [comment]
It may be something that can be added to the docker image / nginx config there. I have seen some other docker images have a flag to specify when using HTTPS or something similar.

**Comment by joecohens** [comment]
@ryanwalls If you are using a load balancer probably you need configure you trustedproxies, you can do it on config/trustedproxies.php

**Comment by jessesanford** [comment]
Also expressing interest in this. It's pretty important to be able to use https in front of cachet.

**Comment by jbrooksuk** [comment]
@jessesanford did the suggestion that @joecohens gave above help?

**Comment by djdefi** [comment]
Master has been updated in #43 to utilize an external nginx container, which allows you to modify the nginx configuration. Hopefully this will help to get around this issue.

**Comment by djdefi** [comment]
Closing this as nginx config is now external.
