### ISSUE TITLE
Nginx conf only accepts localhost connections

### ISSUE THREAD

**Issue by ohaiwalt** [CachetHQ/Docker#144]
Is this working as intended? I'd be happy to submit a PR to make this a bit more flexible.

**Comment by djdefi** [comment]
It seems fine here and in the tests, but I suppose it could be a problem if using host networking when launching the container.

A PR to make this more flexible would be welcome. 👍

**Comment by ohaiwalt** [comment]
I had originally assumed this was partly the source of my issues bringing the container online outside of a development mode, but it appears that was all my issue.
