### ISSUE TITLE
Create new tag with Nginx in app container

### ISSUE THREAD

**Issue by ChrisTerBeke** [CachetHQ/Docker#148]
I really enjoy Cachet, we use it for the status page of our cloud system.

I had some troubles though setting it up on Google Cloud using Docker/Kubernetes, because of the seperate Nginx container in the latest stable Docker image tag.

So I dove in and manually built a container of the current master branch to get it working. Made a blog post which might be interesting for you and other Cachet users
on how to deploy Cachet on Google container engine and get it on an IP address: https://medium.com/@ctbeke/setting-up-cachet-on-google-cloud-817e62916d48#.ce5ddhpuy.

You guys have any plans on making a new tag soon that has Nginx built into the Cachet app container like it is in the master branch right now?

Chris

**Comment by djdefi** [comment]
I believe when upstream releases 2.4 we will be making this tag / change. I didn't want to break 2.3.x with the existing separate container setup.

**Comment by djdefi** [comment]
We are waiting for upstream 2.4 or 2.3.11 before cutting a new tag.

**Comment by djdefi** [comment]
v2.3.11 has bee released
