### ISSUE TITLE
Combine Cachet and nginx in same container

### ISSUE THREAD

**Issue by cbluth** [CachetHQ/Docker#150]
What is the purpose of having separate containers for Cachet and for nginx, wouldnt it be easier to deploy a single container than trying to mount volumes from a different container?

Two containers makes setup a little more complicated when deploying the image via kubernetes.

**Comment by djdefi** [comment]
When 2.4 of Cachet is released, we will be switching to having nginx included.  You can take a look at #129 or the current master branch if you would like to build your own image with nginx onboard.
