### ISSUE TITLE
Failed to use the image

### ISSUE THREAD

**Issue by mykiwi** [CachetHQ/Docker#152]
I try to use the image. I did like this:
```bash
wget https://raw.githubusercontent.com/CachetHQ/Docker/master/docker-compose.yml
sed 's#build: .#image: cachethq/docker:2.3.10#g' docker-compose.yml > fig.yml
docker-compose -f fig.yml up -d
```
You can play these lines on [play-with-docker.com](http://play-with-docker.com) to try by yourself.

Can you tell me what's wrong and why the site is not up?

**Comment by djdefi** [comment]
Hi,

The `docker-compose.yml` uses a `build:` statement, not an `image:`, so it needs to build the container from the Git repository.

You should be able to follow the [Cachet Getting Started with Docker](https://docs.cachethq.io/docs/get-started-with-docker) guide to test the image:

```
git clone https://github.com/cachethq/Docker.git cachet-docker
cd cachet-docker
docker-compose up
```

I was able to successfully launch an instance on http://play-with-docker.com/ with the above commands. Let me know if that does not work for you.

**Comment by mykiwi** [comment]
Hi Ryan,

> The docker-compose.yml uses a build: statement, not an image

Yes, that why my second command create a `fig.yml` file that replace the `build: .` with `image: cachethq/docker:2.3.10`. So the result should be the same, right?

Your commands works. But this repository is used to build the docker hub image, so I should be able to run cachet with only the docker image, no?

**Comment by djdefi** [comment]
The 2.3.10 tag requires an external nginx container, so you will need to use the `docker-compose.yml` from that tag, and also pull down the `nginx-site.conf` like so:

```
wget https://raw.githubusercontent.com/CachetHQ/Docker/v2.3.10/docker-compose.yml
sed -i 's#build: .#image: cachethq/docker:2.3.10#g' docker-compose.yml
mkdir -p conf && wget  https://raw.githubusercontent.com/CachetHQ/Docker/v2.3.10/conf/nginx-site.conf
mv nginx-site.conf conf/
docker-compose up
```

**Comment by mykiwi** [comment]
Thank you 👍
