### ISSUE TITLE
docker-compose install instructions should use cachetdocker_cachet_1 as container reference

### ISSUE THREAD

**Issue by jbayer** [CachetHQ/Docker#155]
after docker-compose up the next two commands currently have the wrong container reference

should be:

```
docker exec -i cachetdocker_cachet_1  php artisan key:generate
docker exec -i cachetdocker_cachet_1  php artisan app:install
```

**Comment by djdefi** [comment]
The prefix is automatically generated depending on the name of the directory you cloned into. So it may be different on every system.

**Comment by jbayer** [comment]
sure, but the default instructions would be best done to match the clone instructions [1] in my opinion. 

`git clone https://github.com/cachethq/Docker.git cachet-docker`

[1] https://github.com/CachetHQ/Docker#development-of-cachet-using-this-docker-environment

**Comment by djdefi** [comment]
Ah right, didn't realize we had diverged there. Will get this fixed up.
