### ISSUE TITLE
Do you have a verison of the docker cachet code for deployment in kubernetes/minikube?

### ISSUE THREAD

**Issue by dyanneo** [CachetHQ/Docker#159]
Trying to adapt cachet and cachet/docker versions 2.3.10 to deploy in minikube and then kubernetes. Do you have updated Dockerfile, deployment.yml, etc. for doing so? Advice on same?
Thanks!

**Comment by gamkiller77** [comment]
I have pushed a PR already for this.  Go look at the openshift folder.  It has the basic info.  If you need more just message me.

[https://github.com/CachetHQ/Docker/tree/master/openshift](url)

**Comment by djdefi** [comment]
Hi @dyanneo please see @gamkiller77's comment ☝️  for the openshift template. I don't have a kubernetes environment myself to test with so any contributions in that regard are much appreciated.

Feel free to reopen if you have any further questions.
