### ISSUE TITLE
Download cachet to /usr/src

### ISSUE THREAD

**Issue by csandanov** [CachetHQ/Docker#161]
Currently, cachet being downloaded to the volume directory and it works ok as long as you specify only container path in the volume (`--volume=/var/www`). However, it's not obvious that it won't work if you specify a host path (e.g. `/var/www/html:/var/www` and some tools like kubernetes do not support volumes without specifying the host path. 

I suggest to download cachet to `/usr/src` (like wordpress guys do) and move it to /var/www in entrypoint if there's no codebase already.

**Comment by djdefi** [comment]
I am wondering if we even need `VOLUME /var/www` in the Dockerfile anymore. It was added to address an issue (#55) with older versions where there was a separate nginx container.

**Comment by djdefi** [comment]
The volume has been removed in master per #165 .

**Comment by csandanov** [comment]
Volume is used to store `.cachet-installed` file so if you restart container it won't try to initialize again.

**Comment by djdefi** [comment]
Thanks @csandanov I forgot about that piece. Going to try to get some tests in place and find a better way to detect that a instance is already configured.

**Comment by csandanov** [comment]
I guess having a whole volume only for this file is not reasonable. My suggestion would be to check if session table exists. Because that's the first table it tries to create and fails when tries to initialize with already initialized database.

**Comment by djdefi** [comment]
#166 addressed this issue and a few other things
