### ISSUE TITLE
checkdbinitpsql function doesnt use DB_DATABASE variable

### ISSUE THREAD

**Issue by dvbavel** [CachetHQ/Docker#177]
If you use the DB_DATABASE environment to define a different DB name the container keeps trying to execute checkdbinitpgsql and trigger an init_db:

>cachet-cachet_1    | Cache cleared!
>cachet-cachet_1    | + check_configured
>cachet-cachet_1    | + case ${DB_DRIVER} in
>cachet-cachet_1    | + checkdbinitpsql
>cachet-cachet_1    | + table=sessions
>cachet-cachet_1    | + export PGPASSWORD=password
>cachet-cachet_1    | + PGPASSWORD=password
>cachet-cachet_1    | ++ psql -h postgres -U cachet -c 'SELECT to_regclass('\''sessions'\'');'
>cachet-cachet_1    | ++ grep -c sessions
>cachet-cachet_1    | psql: FATAL:  database "cachet" does not exist
>cachet-cachet_1    | + '[' 0 -eq 1 ']'
>cachet-cachet_1    | + echo 'Table sessions does not exist! ...'
>cachet-cachet_1    | Table sessions does not exist! ...
>cachet-cachet_1    | + init_db``

My DB is indeed not named cachet, adding a `-d $DB_DATABASE` in line 48 of the entrypoint.sh fixes the problem. e.g. `psql -h ${DB_HOST} -U ${DB_USERNAME} -d ${DB_DATABASE}`

Most likely this issue also is there on mysql or in other routines.

**Comment by djdefi** [comment]
Thanks for the report @dvbavel - should be fixed
