### ISSUE TITLE
docker installation instructions not working

### ISSUE THREAD

**Issue by dtunes** [CachetHQ/Docker#185]
following the instructions provided here (https://docs.cachethq.io/docs/get-started-with-docker) for v2.3.10.

![image](https://cloud.githubusercontent.com/assets/1164234/24534612/97ac245e-162b-11e7-8e32-082615b99aae.png)

**Comment by djdefi** [comment]
I pushed some changes to the docs today, you should be able to clone our `master` branch, then set the `ARG` in [docker-compose.yml](/docker-compose.yml] to `v2.3.10` - This will include a bunch of fixes to the image.

**Comment by djdefi** [comment]
Please open an new issue if you are still having trouble with the latest v2.3.11 release
