### ISSUE TITLE
Question: Why not use different Dockerfiles?

### ISSUE THREAD

**Issue by felixoi** [CachetHQ/Docker#196]
Hello,

I have a short question, maybe there is a good reason for this. Why does this repository use only the Debian Dockerfile and not the different Dockerfiles for NGINX and PHP-FPM? This would be much more structured. For example, you could read the logs of the individual services separately and restart services separately.

Thanks,
felixoi

**Comment by djdefi** [comment]
We had things split out more at one point, but there were issues with shared volumes and a few other things so we just rolled it all into the single container + external DB.

We essentially are following the "one purpose" per container method here, similar to other popular Docker images such as wordpress.

**Comment by J0WI** [comment]
@djdefi would you accept PR to fix that?
