### ISSUE TITLE
Switch to PostgreSQL

### ISSUE THREAD

**Issue by djdefi** [cachethq/Docker#2]
Will need to swap this out in the `docker-compose.yml` and make sure the correct ENV variables are set

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by joecohens** [comment]
:+1:

**Comment by rtrauntvein** [comment]
@cachethq/owners can you please provide an example .env for a Postgres environment? I am not super familiar with Postgres and the docs only seem to mention MySQL

**Comment by jbrooksuk** [comment]
```
DB_DRIVER=pgsql
```

Then just set the usual authentication details to whatever is setup within the container.
