### ISSUE TITLE
Docker-Compose Cachet Container Crashes on Start

### ISSUE THREAD

**Issue by nprail** [CachetHQ/Docker#201]
I decided to install a Cachet instance today and since I'm a Docker fan I decided to go the Docker way. I set all my variables then ran `docker-compose up`. But I am getting an error and am unable to figure out what is causing it. 

Here is the error:
```
cachet_1    | Initializing Cachet container ...
cachet_1    | sed: -e expression #1, char 26: unterminated `s' command
cachetdocker_cachet_1 exited with code 1
```

Would an incorrect variable cause this or are the `sed` commands incorrect? One of my variables does contains a `$`.

Side question:
Should the the APP_KEY include `base64:`?

**Comment by nprail** [comment]
I found the problem. You can't have spaces in the variables because they aren't escaped properly for `sed`.

**Comment by djdefi** [comment]
Hi @nprail - Which variable did you have trouble with? We may be able to fix the quoting there.

The APP_KEY should indeed include `base64:`

**Comment by nprail** [comment]
I had this:
```
MAIL_NAME="Filiosoft Status"
```

And I switched it to this:
```
MAIL_NAME=FiliosoftStatus
```
