### ISSUE TITLE
error 500 connection refused fastcgi

### ISSUE THREAD

**Issue by si458** [CachetHQ/Docker#208]
```
2017/05/26 13:13:26 [error] 56#56: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 10.255.0.2, server: localhost, request: "GET /setup HTTP/1.1", upstream: "fastcgi://[::1]:9000", host: "192.168.168.218:8000"

2017/05/26 13:13:26 [warn] 56#56: *3 upstream server temporarily disabled while connecting to upstream, client: 10.255.0.2, server: localhost, request: "GET /setup HTTP/1.1", upstream: "fastcgi://[::1]:9000", host: "192.168.168.218:8000"
```

any ideas how to fix?

im using DB_TYPE=sqlite instead of postgres

**Comment by riptex** [comment]
I have this issue too. I believe it is tied to a dependency on a PHP version (docker compose) that has other dependency conflicts. (e.g. PHP is incompatible with something else...) -- I've not root caused it.

**Comment by djdefi** [comment]
We really have not done any testing of this image with sqlite. Our test suite only considers Postgres and MySQL.

I will say that the `2017/05/26 13:13:26 [warn] 56#56: *3 upstream server temporarily disabled while connecting to upstream, client: 10.255.0.2, server: localhost, request: "GET /setup HTTP/1.1", upstream: "fastcgi://[::1]:9000", host: "192.168.168.218:8000"` messages are likely a red herring, and not related to `sqlite`.

Are you able to check the Cachet logs within the container and post them here? You can access them via `docker exec`:

```
# Get current logfile name
$ docker exec -it docker_cachet_1 ls storage/logs/
laravel-2017-06-07.log

# cat logfile:
$docker exec -it docker_cachet_1 cat storage/logs/laravel-2017-06-07.log
```

**Comment by si458** [comment]
i will close this issue as i gave up in the end and used postgres linked with the cachet container

from what I found in the .log file, it appears the database.sqlite wasnt being created in the container and wasnt being found if created manually and re-run and also the database wasnt being created either if the file existed?

**Comment by djdefi** [comment]
Thanks @si458 I will open an issue to investigate supporting sqlite in the future.
