### ISSUE TITLE
php-fpm entered FATAL state, too many start retries too quick

### ISSUE THREAD

**Issue by camous** [CachetHQ/Docker#209]
currently trying to use cachethq/docker:2.3.11 with Azure App Service on linux.

Initialization is fine

```
Status: Image is up to date for cachethq/docker:2.3.11
2017-06-03T21:18:09.197371206Z Initializing Cachet container ...
2017-06-03T21:18:09.398458758Z Attempting to connect to database ...
2017-06-03T21:18:09.461009582Z 
2017-06-03T21:18:09.538332019Z Table sessions exists! ...
2017-06-03T21:18:09.538370100Z Starting Cachet! ...
2017-06-03T21:18:10.157574786Z Configuration cache cleared!
2017-06-03T21:18:10.230599172Z Configuration cached successfully!
```

but finally php-fpm fails to start
```
INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
INFO spawned: 'php-fpm' with pid 74
INFO success: queue-worker entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
INFO exited: php-fpm (exit status 78; not expected)
INFO spawned: 'php-fpm' with pid 76
INFO exited: php-fpm (exit status 78; not expected)
INFO gave up: php-fpm entered FATAL state, too many start retries too quickly
```

some reading on internet (https://serverfault.com/questions/786398/how-do-i-start-php7-0-fpm-with-supervisord) I've seen it could be related to a pid file issue.

Reading the DockerFile, I see that php version used is 7 but related "pid" action are referencing php5
```
RUN touch /var/run/nginx.pid /var/run/php5-fpm.pid && \
    chown -R www-data:www-data /var/run/nginx.pid /var/run/php5-fpm.pid
```

Could it be related to php-fpm starting issue ?

**Comment by camous** [comment]
Hum I mixed up github branches, the version I've installed is still on php5 so pid file seems correct.

**Comment by djdefi** [comment]
Hmm not sure why that would be failing. Are you able to `docker exec` into the container, and then run `/usr/sbin/php-fpm7 -c /etc/php7/fpm/pool.d/www.conf` manually from within the container to check for any additional output?

**Comment by camous** [comment]
I can't perform docker exec so far when using the docker container from azure
![image](https://user-images.githubusercontent.com/8566299/26927490-5c28ceb6-4c52-11e7-838c-eb0f0d328eb7.png)

According to App Service on Linux SSH documentation (not sure at 100%), I would have to fork cachet docker and include openssh-server (https://docs.microsoft.com/en-us/azure/app-service-web/app-service-linux-ssh-support, see SSH support with custom Docker images), publish it to docker hub and being able to run manually commands you've suggested. I will try to make asap.

**Comment by djdefi** [comment]
2.3.12 is out, can you please try and let me know if you get a different result?

**Comment by camous** [comment]
switched to 2.3.12 from docker hub without luck.
getting a HTTP 502 bad gateway from nginx (1.13.0)

![image](https://user-images.githubusercontent.com/8566299/27725988-ed4b9cd4-5d78-11e7-89a9-37796f7e6f88.png)

during the initialization, I'm getting those errors, not sure if related.

> 2017-06-30T07:42:26.909434333Z [30-Jun-2017 07:42:26] ALERT: [pool www] user has not been defined
> 2017-06-30T07:42:26.909748589Z [30-Jun-2017 07:42:26] ERROR: failed to post process the configuration
> 2017-06-30T07:42:26.910093561Z [30-Jun-2017 07:42:26] ERROR: failed to post process the configuration

still fighting trying to onboard openssh into cachethq docker image in order to reach SSH from azure. 
https://XXXXXXX.scm.azurewebsites.net/webssh/host
![image](https://user-images.githubusercontent.com/8566299/27726187-a66d3ca4-5d79-11e7-9d39-bbe3e8d45a46.png)

**Comment by wfjsw** [comment]
Probably you should update your config?

**Comment by camous** [comment]
Late answer due to other project priorities. 
Seems that latest version of docker (at least 2.3.12) fixed the issue I was facing (or maybe something changed in azure on linux backend).

**Comment by kirankrishnamurthy** [comment]
I am facing the similar php-fpm error:

Table sessions exists! ...
Starting Cachet! ...
Configuration cache cleared!
Configuration cached successfully!
2017-11-13 22:25:54,735 CRIT Supervisor running as root (no user in config file)
2017-11-13 22:25:54,741 INFO supervisord started with pid 52
2017-11-13 22:25:55,743 INFO spawned: 'nginx' with pid 55
2017-11-13 22:25:55,745 INFO spawned: 'php-fpm' with pid 56
2017-11-13 22:25:55,747 INFO spawned: 'queue-worker' with pid 57
[13-Nov-2017 22:25:55] ALERT: [pool www] user has not been defined
[13-Nov-2017 22:25:55] ALERT: [pool www] user has not been defined
[13-Nov-2017 22:25:55] ERROR: failed to post process the configuration
[13-Nov-2017 22:25:55] ERROR: failed to post process the configuration
[13-Nov-2017 22:25:55] ERROR: FPM initialization failed
[13-Nov-2017 22:25:55] ERROR: FPM initialization failed
2017-11-13 22:25:55,907 INFO exited: php-fpm (exit status 78; not expected)


@camous  Can you please tell me what fix you made.
