### ISSUE TITLE
Support sqlite as a DB driver

### ISSUE THREAD

**Issue by djdefi** [CachetHQ/Docker#210]
Setting sqlite as the `DB_DRIVER` does not work currently, ref: #208

Likely need to look into how to create the database, and set correct variables etc.

**Comment by tonglil** [comment]
@djdefi hey, I did some hacking and was able to get this running with these changes:

https://github.com/tonglil/Docker/tree/sqlite-hacks.

**Comment by djdefi** [comment]
Thanks @tonglil -- It looks like all we would need to do is add the sqlite sb creation bits, and instruct folks to not set the DB credential section?This part seems like it is what allows it to work: https://github.com/CachetHQ/Docker/compare/master...tonglil:sqlite-hacks#diff-b958f585a04af5ee2087610ea7180f34R185

**Comment by djdefi** [comment]
Well, I attempted this, but it is being a pain to add to the test suite. Not sure if it is worth the effort anymore. I am going to close this out, but feel free to pick up my PR #247 if anyone is so inclined and really want sqlite support.
