### ISSUE TITLE
Enable seedfile for auto-deploy in pipelines

### ISSUE THREAD

**Issue by LarsKumbier** [CachetHQ/Docker#212]
In order to have a fully integrated CI/CD-pipeline, we would like to be able to present a seed-file or -command for the customizations like adding components, groups, etc. on the first run.

With the current state, it is not possible to automatically deploy everything from scratch without manual intervention or some really hacky deployment code filling the database directly (and not being future proof) or by simulating API queries.

**Comment by djdefi** [comment]
Seems like this might be something that needs to happen in the upstream Cachet project. /cc: @jbrooksuk

**Comment by wfjsw** [comment]
I think you may resubmit this issue at CachetHQ/Cachet :)

**Comment by LarsKumbier** [comment]
Repostet as https://github.com/CachetHQ/Cachet/issues/2602
