### ISSUE TITLE
Disable nginx caching via environment variable?

### ISSUE THREAD

**Issue by caarlos0** [CachetHQ/Docker#219]
The image's nginx is caching responses, and it seems that it is not possible to change/disable that.

Can we have this configurable via environment variables or something?

**Comment by djdefi** [comment]
Hi @caarlos0 -- Can you give an example of what you are seeing get cached? The caching configuration is in https://github.com/CachetHQ/Docker/blob/master/conf/nginx-site.conf 

We should probably fix it globally and make the content _not_ get cached if it is causing a problem.

**Comment by caarlos0** [comment]
hi @djdefi the problem is the endpoint `/components/id` endpoint.

We have an integration that gets a component to check if there are any incidents, and then open one in case it doesn't. 

Problem is that because of the cache, sometimes it can create multiple incidents...

**Comment by djdefi** [comment]
Opened #220 which I believe will prevent caching of `/components/*` by nginx.

**Comment by caarlos0** [comment]
Let me know when the new version is deployed to docker hub, please :)
