### ISSUE TITLE
docker-compose build not working when configuring postgres_1

### ISSUE THREAD

**Issue by erikng** [CachetHQ/Docker#22]
I am trying to use docker-compose to test out Cachet, however I cannot get it to complete using the latest release.
```
mkdir -p /usr/local/cachet
git clone https://github.com/cachethq/Docker.git cachet-docker /usr/local/cachet
cd cachet-docker
git tag -l
git checkout 2.0.2
docker-compose build
```

During the build, I get the following error:

```
postgres_1 | ERROR: relation "settings" does not exist at character 15
postgres_1 | STATEMENT: select * from "settings"
postgres_1 | ERROR: relation "settings" does not exist at character 15
postgres_1 | STATEMENT: select * from "settings"
cachet_1   | 2015-12-18 17:02:01,998 CRIT repeated unknown pid 221)
```

This error loops and causes the build to not finalize.

**Comment by GrahamCampbell** [comment]
Looks like we're missing 2.0.3 and 2.0.4 too.

**Comment by erikng** [comment]
Looks like `git checkout 2.0.1` works fine.

**Comment by erikng** [comment]
Is this something that will be addressed?

**Comment by djdefi** [comment]
@GrahamCampbell @erikng I have added releases and builds for v2.0.3 and v2.0.4 - Mind giving it a try with the new version?

**Comment by GrahamCampbell** [comment]
@erikng Please can you let us know if this is still broken in v2.0.4.

**Comment by erikng** [comment]
I will test hopefully next Monday if that is okay.

**Comment by djdefi** [comment]
No problem @erikng have a Happy New Year! :tada: :fireworks:

**Comment by erikng** [comment]
I am still having the exact same issue.

**Comment by djdefi** [comment]
Looks like you need to follow the [Cachet getting started with Docker guide](https://docs.cachethq.io/docs/get-started-with-docker)

The database and encryption key must be created using `php artisan` within the container.:

```
$ docker exec -i <Container Name> php artisan migrate --force
$ docker exec -i <Container Name>  php artisan key:generate
$ docker exec -i <Container Name>  php artisan config:cache
```
Replacing `<Container Name> ` with the name of your running Cachet container.  By default when using docker-compose the container name would be `docker_cachet_1`

**Comment by erikng** [comment]
But those steps are after the shell steps. I'm getting stuck prior to this (unless I'm misunderstanding the docker compose guide).

**Comment by djdefi** [comment]
The errors you mentioned are from a running container, not something that would come up during the `docker-compose build` step

**Comment by erikng** [comment]
I assure you it's happening on the docker compose. I will start from scratch tomorrow and outline all the steps and try and recreate it. I was still using the same VM today.

**Comment by djdefi** [comment]
Right, it is from when you ran `docker-compose up`.  

```
postgres_1 | ERROR: relation "settings" does not exist at character 15
postgres_1 | STATEMENT: select * from "settings"
postgres_1 | ERROR: relation "settings" does not exist at character 15
postgres_1 | STATEMENT: select * from "settings"
cachet_1   | 2015-12-18 17:02:01,998 CRIT repeated unknown pid 221)
```

This is output from the `postgres_1` and `cachet_1` containers. docker-compose runs in the foreground unless you specify detached mode `docker compose up -d`.


Open a second terminal, get the name of your Cachet container using `docker ps`:

```
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                  NAMES
06f1e042824d        docker_cachet       "/sbin/entrypoint.sh"    21 minutes ago      Up 21 minutes       0.0.0.0:80->8000/tcp   docker_cachet_1
99773acbbf8b        postgres:9.4.4      "/docker-entrypoint.s"   21 minutes ago      Up 21 minutes       5432/tcp               docker_postgres_1
```

Then initialize the DB

```
docker exec -i docker_cachet_1 php artisan migrate --force
docker exec -i docker_cachet_1  php artisan key:generate
docker exec -i docker_cachet_1  php artisan config:cache
```

**Comment by erikng** [comment]
Okay I understand now. I think in some ways the documentation should explicitly state that postgres errors are expected behavior and you should move on with the shell configuration steps.

When I hit this error, I thought something was wrong, rather than moving on in the steps.
