### ISSUE TITLE
php7-redis is missing

### ISSUE THREAD

**Issue by BirknerAlex** [CachetHQ/Docker#221]
Hello,

I want to use CachetHQ with Redis as Cache but the php7-redis package is missing in the Docker image:

```
[2017-07-19 11:19:28] development.CRITICAL: Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Predis\Client' not found in /var/www/html/vendor/laravel/framework/src/Illuminate/Redis/Database.php:62
```

Can you add this package to the image?

I have no experience with Alpine but I think that would work like that:

```
wget -O /etc/apk/keys/php-alpine.rsa.pub http://php.codecasts.rocks/php-alpine.rsa.pub
echo "@php http://php.codecasts.rocks/v3.5/php-7.0" >> /etc/apk/repositories
apk add --update php7-redis@php
```

Note: The redis package is missing in the community and main repository.

Regards,
Alexander

**Comment by wfjsw** [comment]
Have you tried that by manually install the package into Docker container?

**Comment by BirknerAlex** [comment]
Nope, but I did it now. It seems the package is not compatible to the rest of the php7 packages. :( 

Maybe it would be needed to install all php7 packages from this external repository to get it work together?

**Comment by wfjsw** [comment]
That is really a bad idea :(

**Comment by djdefi** [comment]
>The redis package is missing in the community and main repository.

Not really sure what we can do in this case. I would prefer to only use official Alpine packages if possible.
