### ISSUE TITLE
Update Docker Image in DockerHub

### ISSUE THREAD

**Issue by Madhu1512** [CachetHQ/Docker#235]
Can we get the Updated Cachet Docker Image with Redis Driver?

**Comment by djdefi** [comment]
I kicked off a build of master (`:latest` docker image) and [backported changes to 2.3 branch (`:2.3-latest` docker image)](https://github.com/CachetHQ/Docker/pull/241), which should include redis.

**Comment by solocommand** [comment]
@djdefi These changes didn't make it into the 2.3:latest tag. They are in the 2.3.13 release of @cachethq/cachet, but the latest 2.3 version of the docker image is 2.3.12.

Can we get a 2.3.13 built and get the 2.3-latest tag updated?
