### ISSUE TITLE
Only getting HTTP 500 on docker image, no logs

### ISSUE THREAD

**Issue by StianOvrevage** [CachetHQ/Docker#237]
Trying to run cachethq like this:

`docker run -p 80:8000 --env-file ./cachethq_env cachethq/docker:2.3.12`

cachethq_env-file contains all env-variables.

APP_DEBUG is set to true in attempts to view more logs.

Starting it interactively inside the container:

```
/var/www/html $ /sbin/entrypoint.sh
Initializing Cachet container ...
Attempting to connect to database ...

Table sessions exists! ...
Starting Cachet! ...
Configuration cache cleared!
Configuration cached successfully!
2017-10-13 21:23:56,404 WARN For [program:queue-worker], AUTO logging used for stderr_logfile without rollover, set maxbytes > 0 to avoid filling up filesystem unintentionally
2017-10-13 21:23:56,407 INFO supervisord started with pid 51
2017-10-13 21:23:57,421 INFO spawned: 'nginx' with pid 54
2017-10-13 21:23:57,430 INFO spawned: 'php-fpm' with pid 55
2017-10-13 21:23:57,433 INFO spawned: 'queue-worker' with pid 56
[13-Oct-2017 21:23:57] NOTICE: fpm is running, pid 55
[13-Oct-2017 21:23:57] NOTICE: ready to handle connections
2017-10-13 21:23:58,482 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-10-13 21:23:58,482 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-10-13 21:23:58,482 INFO success: queue-worker entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

Attempting to access http://localhost/ gives the CachetHQ custom HTTP 500 internal server error page.

The only logs available in the container are these:

```
172.17.0.1 - - [13/Oct/2017:21:24:06 +0000] "GET / HTTP/1.1" 500 3165 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36" "-"
2017/10/13 21:24:11 [crit] 58#58: *4 connect() to [::1]:9000 failed (99: Address not available) while connecting to upstream, client: 172.17.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://[::1]:9000", host: "localhost", referrer: "http://localhost/"
2017/10/13 21:24:11 [warn] 58#58: *4 upstream server temporarily disabled while connecting to upstream, client: 172.17.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://[::1]:9000", host: "localhost", referrer: "http://localhost/"
172.17.0.1 - - [13/Oct/2017:21:24:11 +0000] "GET / HTTP/1.1" 500 3165 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36" "-"
```

I'm suspecting some PHP errors. But I don't know where to look for them. The default php7-fpm logs show nothing.

**Comment by djdefi** [comment]
Are you able to check the Cachet logs within the container and post them here? You can access them via `docker exec`:

```
# Get current logfile name

$ docker exec -it docker_cachet_1 ls storage/logs/
laravel-2017-06-07.log

# cat logfile:

$ docker exec -it docker_cachet_1 cat storage/logs/laravel-2017-06-07.log
```

**Comment by erindatkinson** [comment]
I am having the same issue, and no, the logs are not being written to that location.

**Comment by djdefi** [comment]
@erindatkinson that is strange. Is there anything in `storage/logs/` within the container at all?

**Comment by djdefi** [comment]
I just merged a PR that should expose the Cachet application logs within the docker run output.

**Comment by erindatkinson** [comment]
@djdefi that did the trick, thanks!

**Comment by djdefi** [comment]
@StianOvrevage were you able to get it working?

**Comment by StianOvrevage** [comment]
Logs are working now. First got an error about No supported encrypter found. Re-read the install docs and found the info on "Note: You must specify a unique APP_KEY including base64: prefix generated by php artisan key:generate within the container."

Tried `docker run --env-file ./cachethq_env -i -t cachethq/docker:2.3.13 php artisan key:generate` but that threw an error which I suspect was because I was not having a APP_LOG env var defined. Found no info on APP_LOG other than in https://github.com/CachetHQ/Cachet/blob/b2f7ca613b81d8020b54431fee2f3472688a8c7a/config/app.php and set it to errorlog.

Got a new error now since the /var/www/html/.env file exists and is owned by root (shell launched as www-data). Tried executing php artisan as root but then the env-vars were missing. Changed ownership of .env to www-data and changed user and that finally worked.

So what finally worked was:
```
docker run --env-file ./cachethq_env -i -t cachethq/docker:2.3.13 sh
sudo su
chown www-data:www-data .env
exit
php artisan key:generate
```

Would be nice if this could be shortened to one command, for example by changing ownership of .env in the Docker image. And also including the docker run one-liner in the docs.
