### ISSUE TITLE
Subscribers Text Field Not Showing

### ISSUE THREAD

**Issue by f7medina** [CachetHQ/Docker#244]
When the subscriber button is clicked, there is no text field to enter email. We are using the Docker version. Same thing happens when inviting a new team member, and the website for adding a team member loads, two banners show up. I have attached some images too. Any help with these issues would be greatly appreciated. Thanks in advance. 
![email sign up](https://user-images.githubusercontent.com/21961533/31836503-652340cc-b58a-11e7-9980-ba57ac3d328a.png)
![team member sign up](https://user-images.githubusercontent.com/21961533/31836505-666841ee-b58a-11e7-9ee8-10836de0e40a.png)

**Comment by djdefi** [comment]
Are there any errors displayed in your browser developer console? Can you also let me know what version of the image / Cachet release you are running?

**Comment by f7medina** [comment]
We are running v2.3.12 and nothing gets displayed in my browser developer console. This behavior is very strange and we have not been able to figure this out. I thank you for the fast reply.

**Comment by djdefi** [comment]
That is strange. Which MAIL_DRIVER are you using?

**Comment by f7medina** [comment]
The fields were hidden so now I can see the text fields but when filling up form, the new team member cannot login. We are using v2.3.12. Should I open another issue with the new problem? Thanks for replying to my issue.

**Comment by djdefi** [comment]
Email subscribers are separate from Team members (users that can login to the system). I believe they would need to be created `within http(s)://[hostname]/dashboard/team`
