### ISSUE TITLE
Cachet 2.3.13 dockerhub image

### ISSUE THREAD

**Issue by diogonicoleti** [CachetHQ/Docker#250]
Cachet 2.3.13 was released, but the latest 2.3 version of the docker image at DockerHub is 2.3.12 yet. Can you push the 2.3.13 docker image to DockerHub?

**Comment by djdefi** [comment]
Build is running now.

**Comment by diogonicoleti** [comment]
@djdefi i checked that you pushed the `2.3-latest` tag. Is possible to push a tag `2.3.13` too? Here we use version tags instead of `latest` related tags. Thanks!

**Comment by djdefi** [comment]
@diogonicoleti oops sorry! I clicked the trigger button but it seems like it didn't actually launch on Dockerhub 🐳  -  It is on the way now!
![screen shot 2017-11-09 at 12 12 33 pm](https://user-images.githubusercontent.com/3662109/32627445-4c981768-c547-11e7-9505-f5089b336f85.png)

**Comment by diogonicoleti** [comment]
@djdefi already in production here! Thanks.
