### ISSUE TITLE
Anyone even tried to test the image?

### ISSUE THREAD

**Issue by shinespb** [CachetHQ/Docker#259]
Guys, anyone tried to test it?
I tried https://github.com/CachetHQ/Docker/releases/tag/v2.3.13

First of all there is a problem with composer dependencies:
`Installation failed, deleting ./composer.json.
[Composer\Downloader\TransportException]                                                                                                                                     
The "http://packagist.org/p/provider-latest%24ed41eca00ef3d4f7e2841679111c5d1d71458d17416b53328a78aad81a79d42d.json" file could not be downloaded (HTTP/1.1 502 badgateway)`

To fix it you need to insert following string before running installation of hirak/prestissimo
`php /bin/composer.phar config -g repo.packagist composer https://packagist.org && \`

Second - 
`
cachet_1    | Initializing Cachet container ...
cachet_1    | [2017-11-21 11:24:31] {{APP_ENV}}.CRITICAL: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method Illuminate\Foundation\Bootstrap\ConfigureLogging::configure{{APP_LOG}}Handler() in /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/ConfigureLogging.php:59 Stack trace: #0 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/ConfigureLogging.php(29): Illuminate\Foundation\Bootstrap\ConfigureLogging->configureHandlers(Object(Illuminate\Foundation\Application), Object(Illuminate\Log\Writer)) #1 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(203): Illuminate\Foundation\Bootstrap\ConfigureLogging->bootstrap(Object(Illuminate\Foundation\Application)) #2 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(219): Illuminate\Foundation\Application->bootstrapWith(Array) #3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(105): Illuminate\Foundation\Console\Kernel->bootstrap() #4 /var/www/html/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #5 {main} {"identification":{"id":"6259ceac-d6cb-4fe7-987d-b25be2a7a7e9"}} []
`
I thought docker was made to make running simple. You're just running docker-compose build && docker-compose run and you're getting working env.
Are you guys doing testing before release?

**Comment by djdefi** [comment]
> Guys, anyone tried to test it?

Yes, our test suite is in the `tests` directory, and the results can be see here: https://travis-ci.org/CachetHQ/Docker

>First of all there is a problem with composer dependencies: 

I am not able to reproduce this locally or on TravisCI, not sure why this doesn't work for you.

>Second -...

You are missing an `APP_KEY` variable. The [Quickstart Guide](https://github.com/CachetHQ/Docker#quickstart) covers the need to set this variable. It looks like the 2.3.13 image is missing the pretty error handling that announces this if it is not set. 

Building from master and specifying your target Cachet Release in the docker-compose.yml is our preferred method of obtaining an image, so that you always have the latest Image fixes for your version of Cachet.

**Comment by shinespb** [comment]
> I am not able to reproduce this locally or on TravisCI, not sure why this doesn't work for you.
Try to take ubuntu 16.04, install docker.io, docker-compose, git-core and try again. I have the same result even in AWS.
> Building from master 
I'm not building from master. I took a file https://github.com/CachetHQ/Docker/archive/v2.3.13.tar.gz, put it into empty machine, installed docker, docker compose and ran
`
make update-dependencies
make compose-build
`
Btw `RUN echo 'www-data ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers` doesn't make any sense. If you're trying to achieve security and using separate user for serving php, user www-data should not have possibility to elevate privileges.

**Comment by djdefi** [comment]
Ok, so you are doing something we don't say to do in the Readme or Docs, and are surprised we don't specifically test the method that your decided to use? 

Try following our quick start guide, if you have issues, then let us know.

This project is maintained in our free time (mostly mine), so fee free to submit a PR if you feel something needs to be changed. I don't have time to test a non-documented install path.

**Comment by djdefi** [comment]
A new v.2.3.13 tag and Docker hub build have been created, which should fix the `APP_KEY` error message to be much more descriptive.
