### ISSUE TITLE
Branch names inconsistent?

### ISSUE THREAD

**Issue by GrahamCampbell** [CachetHQ/Docker#26]

**Comment by GrahamCampbell** [comment]
I think we should pull the v2.0.0-beta1 release too since we're missing all subsequent releases upto v2.0.0.

**Comment by djdefi** [comment]
@GrahamCampbell I can remove that one - Is it looking better now?

**Comment by GrahamCampbell** [comment]
2.0 should be named 2.0.0, right?

**Comment by GrahamCampbell** [comment]
Also, there's know 1.2.0 branch?

**Comment by GrahamCampbell** [comment]
Do we really need all these branches?

**Comment by GrahamCampbell** [comment]
Would 1.2, 2.0, master not be sufficient?

**Comment by djdefi** [comment]
I like that idea. :point_up: - Would be a lot less to maintain :)

**Comment by djdefi** [comment]
Now we have `base` for the base image, `master` for latest upstream master, `2.0.0` for tagging 2.x.x releases, and `1.2.1` for 1.2.1

**Comment by GrahamCampbell** [comment]
The branches should be called 1.2 and 2.0.

**Comment by GrahamCampbell** [comment]
2.0.0 can't be right, because it should have the 2.0.4 code on it?

**Comment by GrahamCampbell** [comment]
Meh, do we even need branches?

**Comment by GrahamCampbell** [comment]
What's wrong with just generating tags from the master branch?

**Comment by GrahamCampbell** [comment]
Meh, it's just very odd to have 2.0 as a branch, but it doesn't actually contain the 2.0.3 commit in it?

**Comment by GrahamCampbell** [comment]
Don't make anymore changes, lol.

**Comment by djdefi** [comment]
Fixed and fixed, 2.0.4 code is in `2.0`  branch now.

The reason for the branches is:

Master: Pulls upstream master from cachet/cachet (Could be used by a developer potentially to work on upstream)
2.0: pulls 2.0.x releases (mainly to just tag them, if we had done this earlier the `2.0.3` commit would be there also...)

**Comment by GrahamCampbell** [comment]
> 2.0: pulls 2.0.x releases (mainly to just tag them, if we had done this earlier the 2.0.3 commit would be there also...)

Sure. Can we follow that method in future please?

**Comment by GrahamCampbell** [comment]
Also, the master needs rebasing against 2.0 doesn't it?

**Comment by GrahamCampbell** [comment]
There are no more planned 1.x or 2.0.x releases btw. The next release will be in the 2.1.x series.

**Comment by djdefi** [comment]
Definitely will follow this in future, will try to write up a `CONTRIBUTING.md` related to this flow.

Master shouldn't really need a rebase as there hasn't been any changes to the Dockerfile itself, other than changing the release # that it being downloaded. I will double check it though.

**Comment by GrahamCampbell** [comment]
The rebase was mainly for OCD to have it so it's directly applied ontop of 2.0.

**Comment by djdefi** [comment]
:+1:  will see if can fix that up
