### ISSUE TITLE
Change to MySQL from PostgreSQL

### ISSUE THREAD

**Issue by skyfox675** [CachetHQ/Docker#263]
Hello,

After reviewing the KB:
https://docs.cachethq.io/docs/get-started-with-docker

I have updated the docker-compose.yml as follows:
`version: "3"

services:
  cachet:
    build:
      context: .
      args:
        - cachet_ver=master
    ports:
      - 80:8000
      - 3306:3306
    environment:
      - DB_DRIVER=mysql
      - DB_HOST=redacted
      - DB_PORT=redacted
      - DB_DATABASE=redacted
      - DB_USERNAME=redacted
      - DB_PASSWORD=redacted
      - DB_PREFIX=null
      - APP_KEY=${APP_KEY:-null}
      - APP_LOG=errorlog
      - DEBUG=false
    restart: on-failure`

I would like to keep updates/upgrades to future versions as swift as possible. I have tried both the published cachethq docker image as well as the github docker compose version.

docker run command for published container as follows:
`docker run -d --name cachet --net="host" -e DB_DRIVER=mysql -e DB_HOST=redacted -e DB_DATABASE=redacted -e DB_USERNAME=redacted -e DB_PASSWORD=redacted -d cachethq/docker:latest`

Additional info:
MySQL does not reside on the same docker host and is accessible via the host's network.

Please advise on which "install" is more efficient and if I have missed anything.

Thanks!

**Comment by djdefi** [comment]
Here is an example docker-compose.yml for MySQL: https://github.com/CachetHQ/Docker/blob/master/test/docker-compose-mysql.yml

**Comment by skyfox675** [comment]
@djdefi  Thanks for the quick response! Does that configuration work for when the MySQL host is different than the Docker host?
