### ISSUE TITLE
Upgrade to postgres 9.5 for cachet 2.1.0

### ISSUE THREAD

**Issue by GrahamCampbell** [CachetHQ/Docker#27]

**Comment by GrahamCampbell** [comment]
Also, why are we using 9.4.4 and not 9.4.5 already?

**Comment by djdefi** [comment]
9.4.4 was just what was latest at the time or writing.  Can update this for 2.1.0. 

Also I suppose master should just use the `:latest` postgres image.

**Comment by GrahamCampbell** [comment]
No, better to keep it fixed on a tag, since master isn't really meaning "dev", more "2.1.0".

**Comment by GrahamCampbell** [comment]
Postgres 2.5.0 has been released now.
