### ISSUE TITLE
Ignoring HTTPS APP_URL

### ISSUE THREAD

**Issue by denwilliams** [CachetHQ/Docker#271]
I have this running on AWS ECS behind an AWS load balancer:

```
[Browser] -https-> [ELB] -http-> [Container]
```

With the APP_URL env var set to `https://status....`

However when opening the dashboard all the links are `http://status...`. In addition the subscribe form tries to post to `http://...`

I'm not sure what is rewriting the URLs. I haven't specified HTTP anywhere. 
The container itself runs on HTTP.

Any configuration I'm missing, or is something awry here?

**Comment by fotto1** [comment]
I have exactly the same issue any progress on this issue?

**Comment by cit1zen** [comment]
I have the same problem in OpenShift cluster.

**Comment by aberfeldy** [comment]
Same here, seems APP_URL is ignored for creating routes. Only got it working by adding 

`\URL::forceSchema('https');`
to app/Foundation/Providers/AppServiceProvider.php

But using the docker image, I don't want to hack around with the file on deployment. Would be nice if cachet would be using the https in the APP_URL for generating routes.

**Comment by djdefi** [comment]
cc @CachetHQ/core ☝️

**Comment by joecohens** [comment]
APP_URL is just used for console commands at the moment, when installing Cachet behind a load balancer the http/https protocol it's resolved by the TrustedProxies middleware. The config for the trusted ip ranges is at `config/trustedproxies.php`. 

@denwilliams Can you confirm which version of Cachet are you using?

**Comment by aberfeldy** [comment]
Well that's not really working with AWS-ELB's.  ELB's don't really have an IP, they have a pool, which can vary depending on the traffic.

For example at the moment my cachet-ELB is returning 52.58.X.X, 212.86.X.X and 18.196.X.X, calculating the possible range would be impossible. 

A config option, e.g. setting USE_HTTPS to enforce https usage in the app would at least be more helpful in an AWS like environment.

**Comment by denwilliams** [comment]
Sorry @joecohens I missed that question.

I was using `:latest` so not sure what version it was actually running at the time.
I'm now explicitly using `2.3.13` with the same issue.

**Comment by ChrisTerBeke** [comment]
Same issue here on Google Cloud Kubernetes using the Nginx ingress controller (LB level 7).

**Comment by johynpapin** [comment]
Same here using nginx

**Comment by djdefi** [comment]
Reopening here as we should include this in the entrypoint as a possible runtime env option

**Comment by Thomvaill** [comment]
If you are still interested, I posted a Dockerfile example that fixes (in an ugly way) this issue: https://github.com/CachetHQ/Cachet/issues/3952
