### ISSUE TITLE
Change Cachet Documentation

### ISSUE THREAD

**Issue by meyerf99** [CachetHQ/Docker#274]
Hey Cachet Maintainer

Please change your Cachet installation documentation.
Link: https://docs.cachethq.io/docs/installing-cachet
![image](https://user-images.githubusercontent.com/28959963/35644952-b5305898-06ca-11e8-80c4-213c0621b5c6.png)

Replace with:

CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync
CACHET_EMOJI=false

Kind regards,

Flavio

**Comment by djdefi** [comment]
Hey @meyerf99 -- you should be able to suggest edits right from the docs page. 

That docs URL is for the non-Docker Cachet version, so you will want to report this in the https://github.com/CachetHQ/Cachet repo, or directly on the docs website as mentioned above.

cc: @CachetHQ/core

**Comment by jbrooksuk** [comment]
Yeah, you should be able to suggest edits where needed. I'll make this change though.

**Comment by jbrooksuk** [comment]
Done :)
