### ISSUE TITLE
No connector for []

### ISSUE THREAD

**Issue by Dids** [CachetHQ/Docker#29]
After leaving Cachet running overnight for a couple of days, I suddenly started receiving emails that the service is down 99% of the time. I went over to investigate, and there was a rather large logfile filled with the following errors over and over again:
```
#15 {main} {"identification":{"id":"449039c8-03a6-4f66-8f8b-cec9a98e8ec3"}}     
[2016-01-08 06:35:02] production.ERROR: exception 'InvalidArgumentException' wit
h message 'No connector for []' in /var/www/html/vendor/laravel/framework/src/Il
luminate/Queue/QueueManager.php:150
```

**Comment by Dids** [comment]
It seems like the actual downtime might've been due to HAProxy and using the / endpoint as the health check URL instead of, for example, the ping endpoint.

This still doesn't explain the error, though.

**Comment by Dids** [comment]
I think I've got it. I was using 'file' as the queue driver, which seems to have been causing issues in my case. Just switched it back to 'database'', and assuming it's fixed.

**Comment by GrahamCampbell** [comment]
> I was using 'file' as the queue driver,

There is no such driver.
