### ISSUE TITLE
release v2.3.14

### ISSUE THREAD

**Issue by tomplus** [CachetHQ/Docker#292]
Hi guys.

Could you deploy the latest version 2.3.14 as docker image ? There is an important bug fixed.

Thanks!

**Comment by aslepakurov** [comment]
I am doubling this - docker 2.3.13 doesn't have a very important fix with database prefix for metric_points ( #2955).

**Comment by tomplus** [comment]
@aslepakurov I've found a workaround ;) Previous version 2.3.13 works for me without passing an argument `DB_PREFIX`. Try to remove this line: https://github.com/CachetHQ/Docker/blob/f8bccd6fb56203b0f901ad6316c17db9f5ef7a7c/docker-compose.yml#L28

**Comment by aslepakurov** [comment]
@tomplus that should works, thatnks :)

**Comment by djdefi** [comment]
Docker hub builds are running
