### ISSUE TITLE
Building Development Environment Ubuntu 16.04 - Issue

### ISSUE THREAD

**Issue by vstock28021** [CachetHQ/Docker#296]
Using the instructions under Development of Cachet using this docker environment I've ran all the needed commands. When I attempt to run docker-compose up I get the following error below.
System Info: 
Ubuntu 16.04
Docker version 18.03.1-ce, build 9ee9f40
Docker-Compose version 1.18.0, build 8ddd22a9

``vstockwell@noneofyourdamnbusinesst:~/cachet-docker$  docker-compose up
Building cachet
Step 1/22 : FROM debian:jessie
 ---> 4eb8376dc2a3
Step 2/22 : MAINTAINER Alt Three <support@alt-three.com>
 ---> Using cache
 ---> a29e04112b00
Step 3/22 : ARG cachet_ver
 ---> Using cache
 ---> a5112d1d7ed3
Step 4/22 : ENV cachet_ver v2.3.9
 ---> Using cache
 ---> d8c2f5ca04b6
Step 5/22 : RUN DEBIAN_FRONTEND=noninteractive     echo "APT::Install-Recommends \"0\";" >> /etc/apt/apt.conf.d/02recommends &&     echo "APT::Install-Suggests \"0\";" >> /etc/apt/apt.conf.d/02recommends &&     apt-get clean &&     apt-get -q -y update &&     apt-get -q -y install     ca-certificates php5-fpm php5-curl     php5-readline php5-mcrypt sudo     php5-mysql php5-apcu php5-cli     php5-gd php5-mysql php5-pgsql     php5-sqlite wget sqlite git     libsqlite3-dev postgresql-client mysql-client     supervisor cron &&     apt-get clean && apt-get autoremove -q &&     rm -rf /var/lib/apt/lists/* /usr/share/doc /usr/share/man /tmp/*
 ---> Running in 188e40ea40be
E: Could not open lock file /var/cache/apt/archives/lock - open (2: No such file or directory)
E: Unable to lock the download directory
ERROR: Service 'cachet' failed to build: The command '/bin/sh -c DEBIAN_FRONTEND=noninteractive     echo "APT::Install-Recommends \"0\";" >> /etc/apt/apt.conf.d/02recommends &&     echo "APT::Install-Suggests \"0\";" >> /etc/apt/apt.conf.d/02recommends &&     apt-get clean &&     apt-get -q -y update &&     apt-get -q -y install     ca-certificates php5-fpm php5-curl     php5-readline php5-mcrypt sudo     php5-mysql php5-apcu php5-cli     php5-gd php5-mysql php5-pgsql     php5-sqlite wget sqlite git     libsqlite3-dev postgresql-client mysql-client     supervisor cron &&     apt-get clean && apt-get autoremove -q &&     rm -rf /var/lib/apt/lists/* /usr/share/doc /usr/share/man /tmp/*' returned a non-zero code: 100``

If you need more information I would be happy to provide it.

**Comment by djdefi** [comment]
It looks like this is a pretty old version of the image, please make sure you repo is up to date, and let us know if you still have issues.
