### ISSUE TITLE
Setting up mail without authentication

### ISSUE THREAD

**Issue by titansmc** [CachetHQ/Docker#301]
Hi,
I cannot manage to set up mail without authentication, I have the following env variables in our docker-compose.yml

```
    environment:
      - MAIL_DRIVER=smtp
      - MAIL_HOST=smtp.example.com
      - MAIL_ADDRESS=status@example.com
      - MAIL_PORT=25
```

But it keeps asking me for username and password on the setup screen the first time I run it. Isn't i possible?

**Comment by wfjsw** [comment]
I think this question should go to core.

CC @CachetHQ/core

**Comment by titansmc** [comment]
Does it mean I have to do something?

**Comment by wfjsw** [comment]
@titansmc Close this issue and open a new one at CachetHQ/Cachet.
