### ISSUE TITLE
.env file is missing APP_KEY when using the `docker run` stanzas

### ISSUE THREAD

**Issue by JonTheNiceGuy** [CachetHQ/Docker#303]
Following the https://docs.cachethq.io/docs/get-started-with-docker#section-running-cachet-docker-container-manually page, I found that the .env file is missing an APP_KEY= line.

I think the problem is here: https://github.com/CachetHQ/Docker/blob/master/entrypoint.sh#L188-L193

I think the opening line should be:
```
if [ -z "${APP_KEY}" ]; then
```
I've worked around it by dropping into the docker container using `docker exec -it cachet bash` and then `docker restart cachet` once it was done, but I just wanted to flag this for now...

**Comment by wfjsw** [comment]
Confirmed. Empty string is not null in bash.

**Comment by djdefi** [comment]
This breaks the script by default though with docker-compose, as we have it set to `null` as a placeholder there.
