### ISSUE TITLE
Docker and Cachet version 2.3.15

### ISSUE THREAD

**Issue by jwashington104** [CachetHQ/Docker#305]
Hey guys, is there an ETA on having 2.3.15 being made available to build as a docker container?

**Comment by jwashington104** [comment]
Thanks for the update on having v2.3.15 available for use in Docker, however the name of the build is saying this in cachet: 2.3.14-dev when building using the v2.3.15 tag.

**Comment by wfjsw** [comment]
Ugh that's weird.

What build env did you use?

AFAIK release-helper failed to change cachet-ver in docker-compose stuff. It is my mistake for not noticing it.
And the build over hub.docker.com don't have 2.3.15 built. @CachetHQ/core can you have a look?

**Comment by jwashington104** [comment]
This script allows you to pass in the build you want to use, for me I passed in "v2.3.15" directly into the Dockerfile (as that's how I'm building it), see example:

`ENV cachet_ver ${cachet_ver:-v2.3.15}
ENV archive_url ${archive_url:-https://github.com/cachethq/Cachet/archive/${cachet_ver}.tar.gz}
`

**Comment by wfjsw** [comment]
That is weirder.
Have anyone run Cachet without Docker and take a look at the version num?

**Comment by jwashington104** [comment]
@wfjsw, do you know if you've had anything back from this one?

**Comment by djdefi** [comment]
More of a question for the vote Cachet team. We just pull whatever they tag upstream into the image.

**Comment by jbrooksuk** [comment]
I’m on holiday at the moment but can look at this once I’m home. 

I want to do a huge push on 2.4 (becoming 3.0) so that we can get stop supporting 2.3.
