### ISSUE TITLE
Docker and Cachet version 2.3.14 QNAP container station

### ISSUE THREAD

**Issue by KeppensJonas** [CachetHQ/Docker#308]
I have a QNAP with container station installed, I've installed the Cachet Docker container but always when the container is starting I get following error:
Initializing Cachet container ...                                                                                                           
Attempting to connect to database ...                                                                                                       
...........................................................                                                                                 
Could not connect to database server! Aborting... 

How can I fix this?

**Comment by wfjsw** [comment]
Have you spun up a database container and linked them together(if you are not using sqlite)?

**Comment by djdefi** [comment]
We haven't heard back from you, I wanted to check in one last time. If you need anything else at all, just let us know.

For now I'll go ahead and mark this as closed.
