### ISSUE TITLE
Third party with cachet docker-compose image

### ISSUE THREAD

**Issue by miquelbarbero** [CachetHQ/Docker#334]
Sorry if I'm asking a fool question.

We're using your docker-compose-image CacheT and we'd like to add some third-party integrations.

How could we manage that?

We should modify your docker-compose image to add those integrations or we could add them in some other way.

Thanks and kind regards

**Comment by djdefi** [comment]
It depends on how the particular integrations integrate. See https://docs.cachethq.io/docs/addons for examples that of integrations via the Cachet API etc.

If you need to run additional containers, you could add them to your `docker-compose.yml` so they start with the database and app images.

If you need to install additional packages on the Cachet image, you could use this image as a base (`FROM cachethq/docker:latest`).
