### ISSUE TITLE
docker-compose config should be secure by default

### ISSUE THREAD

**Issue by lrstanley** [CachetHQ/Docker#337]
Currently, the docker compose configuration doesn't set `APP_DEBUG=false`, or `APP_ENV=production`. This means a user accessing even something as simple as a page that doesn't exist (404) will see all environment variables, including database credentials, and other sensitive information, due to the Symfony exception page.

**Comment by djdefi** [comment]
@lrstanley I totally agree. Would you like to submit a PR to update those to more secure defaults?
