### ISSUE TITLE
Error 500 after restart the container

### ISSUE THREAD

**Issue by fernandoneto** [CachetHQ/Docker#34]
If i restart the container of cachet when i try to access it im getting this error 
![captura de ecra de 2016-01-14 12 02 37](https://cloud.githubusercontent.com/assets/6515784/12323968/7882ad80-bab7-11e5-8a45-de8ecf0cf552.png)

everything work just perfect before i restart.

**Comment by GrahamCampbell** [comment]
Please show us the log file.

**Comment by fernandoneto** [comment]
```
2016-01-14 11:57:46,230 INFO waiting for cron, nginx, php5-fpm to die
2016-01-14 11:57:46,240 INFO stopped: php5-fpm (exit status 0)
2016-01-14 11:57:46,244 INFO stopped: nginx (exit status 0)
2016-01-14 11:57:46,245 INFO stopped: cron (terminated by SIGTERM)
> rm -f compiled.php config.php routes.php services.json
Loading composer repositories with package information
Installing dependencies from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Nothing to install or update
Generating optimized autoload files
> php artisan optimize --force
Generating optimized class loader
Compiling common classes
> php artisan config:cache
Configuration cache cleared!
Configuration cached successfully!
> php artisan route:cache
Route cache cleared!
Routes cached successfully!
> chmod -R 755 storage
Starting supervisord...
2016-01-14 11:58:07,215 CRIT Supervisor running as root (no user in config file)
2016-01-14 11:58:07,226 INFO RPC interface 'supervisor' initialized
2016-01-14 11:58:07,226 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2016-01-14 11:58:07,226 INFO supervisord started with pid 1
2016-01-14 11:58:08,229 INFO spawned: 'cron' with pid 75
2016-01-14 11:58:08,232 INFO spawned: 'nginx' with pid 76
2016-01-14 11:58:08,234 INFO spawned: 'php5-fpm' with pid 77
2016-01-14 11:58:09,278 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-01-14 11:58:09,278 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-01-14 11:58:09,278 INFO success: php5-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-01-14 11:59:04,651 CRIT reaped unknown pid 104)
2016-01-14 12:00:04,888 CRIT reaped unknown pid 144)
2016-01-14 12:01:05,133 CRIT reaped unknown pid 165)
2016-01-14 12:02:05,364 CRIT reaped unknown pid 186)
2016-01-14 12:03:04,626 CRIT reaped unknown pid 199)
2016-01-14 12:04:04,894 CRIT reaped unknown pid 212)
2016-01-14 12:05:05,115 CRIT reaped unknown pid 225)
2016-01-14 12:06:05,354 CRIT reaped unknown pid 238)
2016-01-14 12:07:04,569 CRIT reaped unknown pid 251)
2016-01-14 12:08:04,797 CRIT reaped unknown pid 264)
2016-01-14 12:09:05,022 CRIT reaped unknown pid 299)
2016-01-14 12:10:05,252 CRIT reaped unknown pid 312)
2016-01-14 12:11:04,747 CRIT reaped unknown pid 325)
2016-01-14 12:12:04,983 CRIT reaped unknown pid 338)
2016-01-14 12:13:05,205 CRIT reaped unknown pid 351)

```

**Comment by jbrooksuk** [comment]
@fernandoneto we're after the `./storage/logs` file content please.

**Comment by fernandoneto** [comment]
i create a [gist](https://gist.github.com/fernandoneto/8e031a5d9a610588be19)

**Comment by GrahamCampbell** [comment]
Looks like you forgot to configure the environment?

**Comment by GrahamCampbell** [comment]
> [2016-01-14 12:15:50] production.ERROR: exception 'RuntimeException' with message 'No supported encrypter found. The cipher and / or key length are invalid.' in /var/www/html/bootstrap/cache/compiled.php:7020
Stack trace:

**Comment by GrahamCampbell** [comment]
That means no encryption key has been set.

**Comment by fernandoneto** [comment]
@GrahamCampbell i fallow your [documentation](https://docs.cachethq.io/docs/get-started-with-docker).
But after stop and start the container this problem appeared.

**Comment by fernandoneto** [comment]
@GrahamCampbell i think i found the problem. in setup i select de cache-driver and session-driver as database. if i select APC(u) the container run without problems after restart.

**Comment by ibandak** [comment]
I'm running into the same problem. I have MySQL as the underlying database, and when choosing Database as the cache and sessions drivers during initial Setup, Cachet docker doesn't restart and gives 500 error, and gives error in laravel logs about the sessions and caches tables not existing in the DB. I did look in the DB and these tables don't exist. So I'm assuming that choosing Database doesn't really create the necessary tables in the DB and hence this fails on restart of docker container.

**Comment by jbrooksuk** [comment]
@GrahamCampbell are we missing a migration?

**Comment by jadametz** [comment]
+1

After attempting to follow the instructions in [Get started with Docker](https://docs.cachethq.io/docs/get-started-with-docker) for both Docker and Docker Compose, I have been unable to successfully run Cachet.

Using just Docker I'm able to get Cachet and MySQL up and running (although MySQL doesn't do any provisioning of the cachet user -- this has to be manually done which clears the errors from Cachet@IP not being able to connect). However, the Cachet application is inaccessible from the browser.

Using Docker Compose I'm able to get the three containers running. However, after the initial setup, upon container restart the application is never accessible again.

*Is there updated documentation on how to currently get the service up and running utilizing Docker or Docker Compose?*

Ideally, I'd be able to author my own `docker-compose.yml` file in order to coordinate Cachet, MySQL, and appropriate volumes for each for use in production.

**Comment by jadametz** [comment]
@jbrooksuk perhaps to your points, after setting up via Docker Compose and restarting the containers, the logs contain an error from Postgres:

```
nginx_1    | 192.168.99.1 - - [05/Apr/2016:19:05:03 +0000] "GET /dashboard HTTP/1.1" 500 3169 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36" "-"
postgres_1 | ERROR:  relation "sessions" does not exist at character 15
postgres_1 | STATEMENT:  select * from "sessions" where "id" = $1 limit 1
```

**Comment by djdefi** [comment]
Not able to reproduce with current master branch, I just fixed #55 which may have been related.

**Comment by djdefi** [comment]
Just re-pushed 2.2.0 tag and Docker hub build - Can you check and reproduce there?

**Comment by ibandak** [comment]
There are migrations missing for sure when using DB as the cache and sessions driver. After consulting the laravel documentation, I was able to get cachet working with a docker container restart by adding these commands after the app:install.

docker exec -it cachet php artisan session:table
docker exec -it cachet php artisan cache:table
docker exec -it cachet php artisan migrate

These commands will create the migrations for the missing caches and sessions tables in the DB.

Regards

**Comment by djdefi** [comment]
Thanks for that info @ibandak - I had only tested with the APC(u) driver myself.

I don't know Laravel really so will need to defer to @jbrooksuk on those command.

**Comment by jadametz** [comment]
Okay, we seem to be making _some_ progress. Here's where I'm at based on the latest information:

Note: commands in succession between two different terminals
```shell
docker-compose up
docker exec -i cachetdocker_cachet_1 php artisan key:generate
docker exec -i cachetdocker_cachet_1 php artisan app:install
```

Navigate to: http://192.168.99.100/setup

![](https://s3.amazonaws.com/f.cl.ly/items/0X0S322x3F2g020T2D3O/Image%202016-04-05%20at%201.42.57%20PM.png?v=7f884837)

```shell
docker-compose stop
docker-compose up
```

Navigate to: http://192.168.99.100/setup

![](https://s3.amazonaws.com/f.cl.ly/items/1V3P3V2v142m2V3X2C2C/Image%202016-04-05%20at%201.44.40%20PM.png?v=35d7e6c3)

Able to complete setup and view empty dashboard.

```shell
docker-compose stop
docker-compose up
```

Navigate to: http://192.168.99.100/ -- successful rendering of timeline
Navigate to: http://192.168.99.100/dashboard -- successful rendering of Login

After login attempt:

![](https://s3.amazonaws.com/f.cl.ly/items/0o3S2Q0T1f3o1f2b2y1s/Image%202016-04-05%20at%201.47.26%20PM.png?v=7af61192)

Docker Compose logs:

```shell
nginx_1    | 192.168.99.1 - - [05/Apr/2016:20:48:18 +0000] "GET /auth/login HTTP/1.1" 200 15213 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36" "-"
postgres_1 | ERROR:  relation "cache" does not exist at character 15
postgres_1 | STATEMENT:  select * from "cache" where "key" = $1 limit 1
nginx_1    | 192.168.99.1 - - [05/Apr/2016:20:48:26 +0000] "POST /auth/login HTTP/1.1" 500 3169 "http://192.168.99.100/auth/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36" "-"
```

**Comment by jadametz** [comment]
@ibandak using the information you provided, here's what I'm getting:

```shell
docker exec -i cachetdocker_cachet_1 php artisan session:table
 Migration created successfully!

docker exec -i cachetdocker_cachet_1 php artisan cache:table
 Migration created successfully!

docker exec -i cachetdocker_cachet_1 php artisan migrate
 **************************************
*     Application In Production!     *
**************************************

Command Cancelled!
```

Navigate to http://192.168.99.100/setup -- Error 500

```shell
docker-compose stop
docker-compose up
```

Navigate to http://192.168.99.100/setup -- Success -- complete setup with Database as cache and session driver

```shell
docker-compose stop
docker-compose up
```

Navigate to: http://192.168.99.100/ -- successful rendering of timeline
Navigate to: http://192.168.99.100/dashboard -- successful rendering of Login

After login attempt:
Same as above comment. 500 and Docker Compose logs reference `"cache does not exist"`.

**Comment by ibandak** [comment]
@jadametz, why did you Cancel out of the prompt?

docker exec -it cachet php artisan migrate

**************************************
*     Application In Production!     *
**************************************

put "y" for yes and let it complete so it creates the tables, migrate will not destroy anything else it'll only create the 2 new tables..

**Comment by ibandak** [comment]
@jadametz , If you use the "--force" flag that will make it run without a prompt on production:
docker exec -it cachet php artisan migrate --force

**Comment by djdefi** [comment]
Ran some tests around this on the latest version of master, please check out #58

**Comment by jadametz** [comment]
@djdefi looks like the changes you mentioned in #58 for initializing on initial "up", etc. all worked well. However, after restart of the containers I'm not able to login with the username provided during setup.

```shell
nginx_1    | 192.168.99.1 - - [11/Apr/2016:20:13:24 +0000] "GET /dashboard HTTP/1.1" 302 384 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36" "-"
nginx_1    | 192.168.99.1 - - [11/Apr/2016:20:13:24 +0000] "GET /auth/login HTTP/1.1" 200 15214 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36" "-"
nginx_1    | 192.168.99.1 - - [11/Apr/2016:20:13:24 +0000] "GET /build/dist/css/all-5d444fe92b.css HTTP/1.1" 304 0 "http://192.168.99.100/auth/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36" "-"
nginx_1    | 192.168.99.1 - - [11/Apr/2016:20:13:24 +0000] "GET /build/dist/js/all-84f6fb9f0b.js HTTP/1.1" 304 0 "http://192.168.99.100/auth/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36" "-"
nginx_1    | 192.168.99.1 - - [11/Apr/2016:20:13:24 +0000] "GET /fonts/ionicons.ttf?v=2.0.0 HTTP/1.1" 304 0 "http://192.168.99.100/auth/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36" "-"
postgres_1 | ERROR:  relation "cache" does not exist at character 15
postgres_1 | STATEMENT:  select * from "cache" where "key" = $1 limit 1
nginx_1    | 192.168.99.1 - - [11/Apr/2016:20:13:27 +0000] "POST /auth/login HTTP/1.1" 500 3169 "http://192.168.99.100/auth/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36" "-"
```

**Comment by djdefi** [comment]
Thanks for testing @jadametz - I was getting that same error using cache drivers other than APC(u) - I see above that you were using the "database" driver which I was not able to get working in my tests. Are you still using that driver?

 I'm no laravel expert so not really sure what is missing from the Docker image for the other cache and session drivers to work...

**Comment by jadametz** [comment]
Yes, still using the database driver. To be honest, I'm not sure what these drivers are totally doing so if there's documentation somewhere that I'm missing, I'd love a link :smile:

**Comment by djdefi** [comment]
@jadametz https://docs.cachethq.io/docs/prerequisites is all I know of. That lists APCu and Redis (I have not tested Redis personally).

**Comment by djdefi** [comment]
All defaults should be set now (see #63).

Please open a new issue if you are still having problems with the latest master.
