### ISSUE TITLE
Dockerfile for "cachethq/docker:base-5a0320b"?

### ISSUE THREAD

**Issue by andygrunwald** [CachetHQ/Docker#35]
Hey,

the Dockerfile is based upon `FROM cachethq/docker:base-5a0320b`.
Where can i find the definition of the image `cachethq/docker:base-5a0320b`?

**Comment by andygrunwald** [comment]
I found it here: https://github.com/CachetHQ/Docker/blob/base-5a0320b/Dockerfile

There my question is: Why this is not included in the original Dockerfile?

**Comment by djdefi** [comment]
Mainly to help speed up builds for testing different versions. See #4 and #1.

At this point it isn't really needed I suppose, as the longest build step is the Cachet install anyway. Maybe we will kill this for 2.1.0 or something.

**Comment by andygrunwald** [comment]
This would be great. In my opinion the build speed is not so important, because everything is automated via docker hub. And in the end you don`t build this image every minute, so it has the advantage to create a bigger transparency how this image is build

**Comment by andygrunwald** [comment]
Should i drop a PR?

**Comment by djdefi** [comment]
Sure 👍

**Comment by andygrunwald** [comment]
Why are there `ca-certificates` and `git` installed? Are they in use?
I think they can be removed, or am i wrong?

Checkout the PR here: https://github.com/CachetHQ/Docker/pull/37

**Comment by djdefi** [comment]
@andygrunwald I believe that is leftover from doing git clone rather than downloading the release archives.  Feel free to remove if it is not needed :)

**Comment by jbrooksuk** [comment]
:+1:
