### ISSUE TITLE
PHP 7.0 is EOL

### ISSUE THREAD

**Issue by ashleyprimo** [CachetHQ/Docker#353]
**PHP 7.0** is now **End of Life**- this should be updated to a supported version -> https://www.php.net/supported-versions.php

**Comment by djdefi** [comment]
Can you confirm which tag you are using? Buiding off recent master I am showing at least 7.3.14

```
$ docker exec docker_cachet_1 php -v
PHP 7.3.14 (cli) (built: Jan 27 2020 21:55:23) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.14, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.14, Copyright (c) 1999-2018, by Zend Technologies
```

**Comment by ashleyprimo** [comment]
Yes, it appears that the [alpine package](https://pkgs.alpinelinux.org/package/edge/community/x86/php7) for PHP7 has since been updated to a supported version :)
