### ISSUE TITLE
Busybox sendmail does not support argument "b"

### ISSUE THREAD

**Issue by SC-cmarquardt** [CachetHQ/Docker#357]
Hi,

the Swiftmailer Implementation uses as default sendmail command `/user/sbin/sendmail -bs` . But the sendmail implementation in the busybox does not support the argument -b.

Kind regards,
Christopher

**Comment by djdefi** [comment]
Would adding the `ssmtp` package work? https://pkgs.alpinelinux.org/contents?file=sendmail&path=&name=&branch=edge

**Comment by Stunkymonkey** [comment]
its not about the part that is coming after/below sendmail. its about sendmail itself.
```
bash-5.0# sendmail -bs
sendmail: unrecognized option: b
BusyBox v1.30.1 (2019-10-26 11:23:07 UTC) multi-call binary.
...
```

**Comment by Stunkymonkey** [comment]
I guess this is the origin of the problem: [Cachet:config/mail.php#:111](https://github.com/CachetHQ/Cachet/blob/2.4/config/mail.php#L111)

**Comment by Stunkymonkey** [comment]
adding `postfix` does not raise an error with `-bs`

but I have not yet tested if this can send an email

**Comment by Stunkymonkey** [comment]
can confirm, that my PR fixed the issue with sendmail. Have successfully verified my email.

**Comment by djdefi** [comment]
Thanks for looking into that and the PR @Stunkymonkey 

Going to close this but let me know if I have misunderstood.
