### ISSUE TITLE
Displaying a metric on the dashboard fails with error 500 code

### ISSUE THREAD

**Issue by jonathon2nd** [CachetHQ/Docker#365]
Issue on Cachet repo: https://github.com/CachetHQ/Cachet/issues/3920
Using Cachet docker version 2.4.

I created metric a metric in cachet, viewing it in the dashboard results in 500 error in the browser console,
```
Request URL: https://status-test.example.com/metrics/1
Request Method: GET
Status Code: 500 
```
with graph 'Loading Data'. 
![image](https://user-images.githubusercontent.com/52681917/74576967-bd4bde80-4f52-11ea-96fc-33db39874274.png)

Not seeing any errors in cachet or postgres.

I have been digging around in the various open and closed issues in both repos, and have not been able to identify a fix which works. 

I am sorry if I am missing something, any help would be appreciated.

**Comment by jonathon2nd** [comment]
This is caused by a problem with cachet https://github.com/CachetHQ/Cachet/issues/3254. By adding https://github.com/CachetHQ/Cachet/pull/3830 and building docker image using it, I was able to resolve this issues. Looking to see if the pull will be merged

**Comment by kepikoi** [comment]
Hey, I'm still experiening this issue using the docker image `cachethq/docker` and software version  `2.4.0-dev`. Since this issue has been closed, I'm wodering about the progress of this. As far as I can see @jonathon2nd's https://github.com/CachetHQ/Cachet/pull/3830 is still not merged

**Comment by kepikoi** [comment]
Den Postman API Key kannst du hier erstellen https://tangany.postman.co/settings/me/api-keys

**Comment by kascodingNL** [comment]
> Hey, I'm still experiening this issue using the docker image `cachethq/docker` and software version `2.4.0-dev`. Since this issue has been closed, I'm wodering about the progress of this. As far as I can see @jonathon2nd's [CachetHQ/Cachet#3830](https://github.com/CachetHQ/Cachet/pull/3830) is still not merged

I've got it too!

**Comment by djdefi** [comment]
https://github.com/CachetHQ/Cachet/pull/3830 would be the issue to bump. This Docker image just packages the upstream Cachet project.
