### ISSUE TITLE
Create a Base image

### ISSUE THREAD

**Issue by rtrauntvein** [cachethq/Docker#4]
We should have a base image that does all of the apt-get installs and other configurations.

Then we would use this as the `FROM` for the images that pull down Cachet, and do the composer install and finalization.

**Comment by wfjsw** [comment]
Is wfjsw/Cachet-Docker-Base ok?

**Comment by wfjsw** [comment]
CI finished with some errors
```
mv: cannot stat '/var/www/html/docker/php-fpm-pool.conf': No such file or directory
mv: cannot stat '/var/www/html/docker/nginx-site.conf': No such file or directory
rm: cannot remove '/var/www/html/docker': No such file or directory
```

**Comment by wfjsw** [comment]
Fixed :)

**Comment by rtrauntvein** [comment]
Should we move that into this repo under a subfolder named `base` - Then we can make a docker hub build pointed at that directory called `cachethq/cachet:base` 

Then the images built from that would start with `FROM cachethq/cachet:base`

**Comment by wfjsw** [comment]
Is that ok? I will make the change in minutes :p

**Comment by wfjsw** [comment]
I gonna build a test Cachet in top of it before I publicly release that.

**Comment by wfjsw** [comment]
Oops, it cause my CI broke

**Comment by rtrauntvein** [comment]
No worries @wfjsw - Looks like you are off to a good start :)

**Comment by jbrooksuk** [comment]
If you need a new repo creating let me know.

**Comment by wfjsw** [comment]
Image built successfully. Need some test (run phpunit?)

**Comment by wfjsw** [comment]
done.
