### ISSUE TITLE
Stepping away from the project.

### ISSUE THREAD

**Issue by djdefi** [cachethq/Docker#402]
Greetings 👋🏻 

I'm @djdefi and I [created the Docker image for Cachet](https://github.com/CachetHQ/Docker/commit/0698357d2ce93f5b7ddc44901a2f7113f356ba6b) back in 2015 to implement Cachet as a status page for the company I worked for at the time, and have been the semi-official maintainer of this Docker image since.

Shortly after that, I took a new job as a Support Engineer at GitHub, and no longer personally had a need to run Cachet. I continued to push the Docker image along as a side project when I was able. As time has gone on, I've been able to contribute less and less, and with no "production" need for it, I essentially stopped being active here.

Just wanted to drop a note here to say that I no longer have access to the repository or Docker hub, and I don't know what the maintainership status is going forward. 

Thank you to everyone [who contributed over the years](https://github.com/CachetHQ/Docker/graphs/contributors), hopefully this project was helpful to you in some way. This was the largest open source project I have ever attempted to maintain, and ya'll made it possible.

- ☮️ ❤️ :octocat:  @djdefi

**Comment by apinter** [comment]
> Greetings 👋🏻
> 
> I'm @djdefi and I [created the Docker image for Cachet](https://github.com/CachetHQ/Docker/commit/0698357d2ce93f5b7ddc44901a2f7113f356ba6b) back in 2015 to implement Cachet as a status page for the company I worked for at the time, and have been the semi-official maintainer of this Docker image since.
> 
> Shortly after that, I took a new job as a Support Engineer at GitHub, and no longer personally had a need to run Cachet. I continued to push the Docker image along as a side project when I was able. As time has gone on, I've been able to contribute less and less, and with no "production" need for it, I essentially stopped being active here.
> 
> Just wanted to drop a note here to say that I no longer have access to the repository or Docker hub, and I don't know what the maintainership status is going forward.
> 
> Thank you to everyone [who contributed over the years](https://github.com/CachetHQ/Docker/graphs/contributors), hopefully this project was helpful to you in some way. This was the largest open source project I have ever attempted to maintain, and ya'll made it possible.
> 
> * peace_symbol heart :octocat:  @djdefi

Sad to see you go, but I hope you will have a lot of fun and success going forward! I personally want to thank you for maintaining the docker image as I use it at the co. I work at. Really appreciate your work!


P.S.: Going to try and fix the current problems and make a PR next week. **EDIT:** which I noticed that someone already did. Who will maintain the repo in the future?
