### ISSUE TITLE
Error building.

### ISSUE THREAD

**Issue by Justinzobel** [cachethq/Docker#407]
---> Running in ed364571ebf7
--2021-03-28 09:57:17--  https://github.com/cachethq/Cachet/archive/2.3.18.tar.gz
Resolving github.com... 13.236.229.21
Connecting to github.com|13.236.229.21|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/CachetHQ/Cachet/tar.gz/2.3.18 [following]
--2021-03-28 09:57:17--  https://codeload.github.com/CachetHQ/Cachet/tar.gz/2.3.18
Resolving codeload.github.com... 54.79.46.55
Connecting to codeload.github.com|54.79.46.55|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-03-28 09:57:18 ERROR 404: Not Found.

ERROR: Service 'cachet' failed to build: The command '/bin/sh -c wget ${archive_url} &&     tar xzf ${cachet_ver}.tar.gz --strip-components=1 &&     chown -R www-data:root /var/www/html &&     rm -r ${cachet_ver}.tar.gz &&     php /bin/composer.phar global require "hirak/prestissimo:^0.3" &&     php /bin/composer.phar install -o &&     rm -rf bootstrap/cache/*' returned a non-zero code: 8

**Comment by esteban1983cl** [comment]
Hi try this !!

```yaml
cachet:
    build:
      context: .
      args:
        - cachet_ver=v2.3.18
```

**Comment by Justinzobel** [comment]
Thanks for the comment, I have since moved on to other projects. I will close this as no other user has reported the same issue.
