### ISSUE TITLE
nginx as container instead internal instance

### ISSUE THREAD

**Issue by zemirco** [CachetHQ/Docker#43]
Hey,

cachet is pretty cool and especially this Docker version makes it very easy to get started. Great work!

I'm currently trying to setup `https://...`. Currently nginx is tightly integrated into the dockerfile. Wouldn't it be better / more flexible to use a separate nginx container via docker-compose? That would allow for using a custom nginx setup with ssl termination etc. 

At the moment I would need a second nginx instance to handle ssl, i.e. `nginx ssl` -> `internal nginx` -> `cachet`.

If that's OK with you I'll start working on a pull request.

**Comment by djdefi** [comment]
Sounds great to me, as long as we don't need to build and maintain our own custom nginx / fpm images and can use official ones.

**Comment by zemirco** [comment]
Sent a pull request https://github.com/CachetHQ/Docker/pull/46

**Comment by djdefi** [comment]
Implemented in #46
