### ISSUE TITLE
Exception when trying upgrade Cachet version

### ISSUE THREAD

**Issue by ephillipe** [CachetHQ/Docker#54]
I'm using cachethq/docker:2.1.2

Actual behaviour

Frontpage is working, but not dashboard.

I find a log into running docker container, but I found only this:

`Next ErrorException: Undefined variable: has_component (View: /var/www/html/resources/views/emails/incidents/new-html.blade.php) in /var/www/html/storage/framework/views/e59fc647d09d2e979cfd23287fc2761b56247257.php:13
Stack trace:
#0 /var/www/html/bootstrap/cache/compiled.php(14880): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 0)
#1 /var/www/html/bootstrap/cache/compiled.php(14915): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/html/s...', Array)
#2 /var/www/html/bootstrap/cache/compiled.php(14747): Illuminate\View\Engines\CompilerEngine->get('/var/www/html/r...', Array)
#3 /var/www/html/bootstrap/cache/compiled.php(14735): Illuminate\View\View->getContents()
#4 /var/www/html/bootstrap/cache/compiled.php(14719): Illuminate\View\View->renderContents()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(439): Illuminate\View\View->render()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(323): Illuminate\Mail\Mailer->getView('emails.incident...', Array)
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(163): Illuminate\Mail\Mailer->addContent(Object(Illuminate\Mail\Message), 'emails.incident...', 'emails.incident...', NULL, Array)
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(278): Illuminate\Mail\Mailer->send('emails.incident...', Array, Object(Closure))
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(129): Illuminate\Mail\Mailer->handleQueuedMessage(Object(Illuminate\Queue\Jobs\DatabaseJob), Array)
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Jobs/DatabaseJob.php(50): Illuminate\Queue\Jobs\Job->resolveAndFire(Array)
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(208): Illuminate\Queue\Jobs\DatabaseJob->fire()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(158): Illuminate\Queue\Worker->process('database', Object(Illuminate\Queue\Jobs\DatabaseJob), '3', 0)
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(109): Illuminate\Queue\Worker->pop(NULL, NULL, 0, '3', '3')
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(71): Illuminate\Queue\Console\WorkCommand->runWorker(NULL, NULL, 0, 128, false)
#15 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
#16 /var/www/html/bootstrap/cache/compiled.php(1232): call_user_func_array(Array, Array)
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#18 /var/www/html/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/html/vendor/symfony/console/Application.php(791): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/html/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/html/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /var/www/html/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 {main} {"identification":{"id":"009bc5ee-ab6c-4760-8289-dea8cccf6dc2"}}`

**Comment by djdefi** [comment]
Can you check out the latest master branch version and let me know if this persists?

**Comment by djdefi** [comment]
Closing, please open a new issue if this still occurs using master.
