### ISSUE TITLE
Missing webserver on latest image

### ISSUE THREAD

**Issue by spinolacastro** [CachetHQ/Docker#56]
Hello, i've followed the [doc](https://docs.cachethq.io/docs/get-started-with-docker) but looks like the nginx webserver is missing, the Cached container listens only the fpm port (9000) there isn't any process listening on 8000. I found out the nginx config was removed from Dockerfile couple weeks ago, am i doing something wrong or the doc is missing some steps?

> MacBook-Pro-de-Diego:Downloads diego$ docker port cachet
> 8000/tcp -> 0.0.0.0:80

> MacBook-Pro-de-Diego:Downloads diego$ docker top cachet
> UID                 PID                 PPID                C                   STIME               TTY                 TIME                CMD
> root                1804                1275                0                   12:41               ?                   00:00:00            /usr/bin/python /usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf
> root                1873                1804                0                   12:41               ?                   00:00:00            /usr/sbin/cron -f
> root                1874                1804                0                   12:41               ?                   00:00:00            php-fpm: master process (/etc/php/7.0/fpm/php-fpm.conf)
> 33                  1875                1874                0                   12:41               ?                   00:00:00            php-fpm: pool www
> 33                  1876                1874                0                   12:41               ?                   00:00:00            php-fpm: pool www

> MacBook-Pro-de-Diego:Downloads diego$ curl http://$(docker-machine ip)/setup -v
> *   Trying 192.168.99.100...
> * connect to 192.168.99.100 port 80 failed: Connection refused
> * Failed to connect to 192.168.99.100 port 80: Connection refused
> * Closing connection 0
> curl: (7) Failed to connect to 192.168.99.100 port 80: Connection refused

**Comment by spinolacastro** [comment]
Nvm, just found docker-composer doc.

**Comment by adamlc** [comment]
This isn't actually documented anywhere which is kind of annoying. Just spent the last hour trying to figure this out. The documentation needs updating to reflect this :/

**Comment by djdefi** [comment]
@adamlc Sorry about that! I have submitted an update to the online documentation to add the nginx container in there.

**Comment by jbrooksuk** [comment]
@djdefi merged. If I can get your email, I'll add you as a contributor.

**Comment by jbrooksuk** [comment]
Sent to your gmail.
