### ISSUE TITLE
PHP-APC is not included to docker container

### ISSUE THREAD

**Issue by jbrooksuk** [CachetHQ/Docker#57]
> Copied from https://github.com/CachetHQ/Cachet/issues/1694

Hi I noticed that Cachet container does not has `php-apcu` package so if user choose APCu as cache module he would get 500 error.

Debian Sid has `php-apcu` [deb package](https://packages.debian.org/sid/php5-apcu) in official repository so we can just add this package name  in Docker file.

### Your setup

- I use Docker compose for version 2.2
- Cachet 2.2
- Database Postgres
- PHP 7

### Actual behaviour

Cachet not wors and generate 500 error after docker container restart.
```
[2016-04-07 21:29:18] production.CRITICAL: Symfony\Component\Debug\Exception\FatalThrowableError: Fatal error: Call to undefined function Illuminate\Cache\apc_fetch() in /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/ApcWrapper.php:32

```

### Steps to reproduce

Follow docker-compose installation guide and chose APCu as cache module. Then restart docker container.

**Comment by djdefi** [comment]
Looks like we missed this when we switched to php 7.

**Comment by djdefi** [comment]
Taking a closer look, there is no official Debian sid package for a PHP 7 APCu module. The one linked above is for php5.

**Comment by djdefi** [comment]
Ugh, APC with PHP 7 on Sid is painful. I am likely roll the base image back to Jessie so we can have a vendor package until PHP 7 and APC has better support.
