### ISSUE TITLE
Kitematic issues

### ISSUE THREAD

**Issue by jbrooksuk** [CachetHQ/Docker#77]
![image](https://cloud.githubusercontent.com/assets/246103/15538124/22d8cd10-2272-11e6-950d-139c92839b23.png)

**Comment by Jamie-Owen** [comment]
I expect this may be because you aren't running a mysql container for cachet to link to.

**Comment by jbrooksuk** [comment]
Should Docker be using Postgres though?

**Comment by GrahamCampbell** [comment]
Yeh, it should be using postgres.

**Comment by Jamie-Owen** [comment]
Should probably be the default on line 37 & 38 in [entrypoint.sh](https://github.com/CachetHQ/Docker/blob/master/docker/entrypoint.sh#L37) then?

**Comment by jbrooksuk** [comment]
It should if we're installing Postgres.

**Comment by djdefi** [comment]
Hmm the `docker-compose.yml` should be pulling Postgres and NGINX images as well and setting the ENV variables needed. I don't use Kitematic myself so I am not sure how `docker-compose` support works exactly.

**Comment by djdefi** [comment]
@jbrooksuk I just downloaded Kitematic, it doesn't appear to have native docker-compose support, so you will need to run `docker-compose up` from the Docker CLI.

Once up and running the containers do show up in Kitematic:

![screen shot 2016-05-27 at 4 00 56 pm](https://cloud.githubusercontent.com/assets/3662109/15623045/47bdbae2-2424-11e6-8772-0b5bc54289b7.png)

**Comment by jbrooksuk** [comment]
Okay. Is there anyway that we can get that to work? Kitematic lists Cachet, but it doesn't work, so it's a bit weird.

**Comment by djdefi** [comment]
https://github.com/docker/kitematic/issues/137

Until kitematic ships docker-compose support in the GUI, not a lot we can do.

Only way it would work straight out of Kitematic would be to put everything into a single image (Postgres and all). 

Essentially any Docker image that uses best practices for one service per container cannot be run via kitematic without going to CLI. The official Wordpress image for example requires a linked MySQL image, which would need to be launched manually or through Docker compose on the CLI for it to work.

Kitematic is lacking too many Docker ecosystem features currently. It is fine for people new to docker, but is not something suited for real production use.

**Comment by djdefi** [comment]
We could probably add some logic to the startup to look for a linked DB container, and display a better warning if one is not present.

**Comment by djdefi** [comment]
After digging into this a bit more this is not really something we can fix on our side beyond making the error message more user friendly. (Personally I would rather have the raw error displayed though)

Looking at the popular Wordpress Docker image, the behavior is very much the same when launching out of Kitematic's UI:

![screen shot 2016-06-01 at 10 56 27 am](https://cloud.githubusercontent.com/assets/3662109/15723371/f60aa71a-27f6-11e6-8b0b-445bcd0e2283.png)

Going to go ahead and close this out as `wontfix`

**Comment by jbrooksuk** [comment]
No problem! :)
