### ISSUE TITLE
Delete 1.1 tag

### ISSUE THREAD

**Issue by GrahamCampbell** [cachethq/Docker#8]

**Comment by rtrauntvein** [comment]
Done, added 1.2 tag also

**Comment by GrahamCampbell** [comment]
1.2 can't be tagged until we actually release 1.2 on cachet

**Comment by GrahamCampbell** [comment]
could you delete that please

**Comment by GrahamCampbell** [comment]
> wget https://github.com/cachethq/Cachet/archive/1.2.tar.gz && \

That code there is wrong you see.

**Comment by GrahamCampbell** [comment]
We need to actually download the v1.2.0 tag, that doesn't exist yet.

**Comment by wfjsw** [comment]
It downloads the 1.2 branch ATM for test
