### ISSUE TITLE
QA testing suite

### ISSUE THREAD

**Issue by djdefi** [CachetHQ/Docker#83]
Basic release QA tests to run.

- [x] Build and launch `docker-compose up`
- [x] Initial setup with via `php artisan cachet:seed`
- [x] Verify Login
- [x] Create Component
- [x] Create incident
- [x] Stop all containers

**Comment by djdefi** [comment]
@jbrooksuk @GrahamCampbell are there any other items you can think of that we should be testing for?

**Comment by jbrooksuk** [comment]
You could see whether `php artisan cachet:seed` runs okay. That's how we power our demo.

**Comment by djdefi** [comment]
@jbrooksuk `php artisan cachet:seed` is great!

**Comment by djdefi** [comment]
@jbrooksuk I see there are some tests in https://github.com/CachetHQ/Cachet/tree/2.3/tests - Would there be any value in running those here as well?

**Comment by djdefi** [comment]
Automated testing in #90 - We can easily add more tests if there is anything else identified. ⚡
