### ISSUE TITLE
Multiply containers?

### ISSUE THREAD

**Issue by kjetilpp** [CachetHQ/Docker#86]
Sorry if it's wrong to ask here.
How can I run several seperate docker with cachet on the same server.

**Comment by djdefi** [comment]
You can run the nginx container on a separate port. If you are using `docker-compose` you can change port `80` to whatever port you want to have Cachet served on here: https://github.com/CachetHQ/Docker/blob/master/docker-compose.yml#L9

Please see the [Docker run reference](https://docs.docker.com/engine/reference/run/) guide for more details on this and running Docker containers in general.

**Comment by djdefi** [comment]
Feel free to re-open if you have any further questions.
